// Forced-alignment RPC: aligns narration text to an existing audio asset
// and produces a timed-segment output (e.g. for subtitle/caption assets).
// Same presigned-URL contract as tts.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/align.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	AudioGetUrl   string                 `protobuf:"bytes,2,opt,name=audio_get_url,json=audioGetUrl,proto3" json:"audio_get_url,omitempty"` // presigned GET for the source audio asset
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	OutputPutUrl  string                 `protobuf:"bytes,4,opt,name=output_put_url,json=outputPutUrl,proto3" json:"output_put_url,omitempty"` // presigned PUT for the resulting alignment JSON
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignRequest) Reset() {
	*x = AlignRequest{}
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignRequest) ProtoMessage() {}

func (x *AlignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignRequest.ProtoReflect.Descriptor instead.
func (*AlignRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_align_proto_rawDescGZIP(), []int{0}
}

func (x *AlignRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *AlignRequest) GetAudioGetUrl() string {
	if x != nil {
		return x.AudioGetUrl
	}
	return ""
}

func (x *AlignRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AlignRequest) GetOutputPutUrl() string {
	if x != nil {
		return x.OutputPutUrl
	}
	return ""
}

func (x *AlignRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AlignProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pct           int32                  `protobuf:"varint,1,opt,name=pct,proto3" json:"pct,omitempty"`
	EtaS          int32                  `protobuf:"varint,2,opt,name=eta_s,json=etaS,proto3" json:"eta_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignProgress) Reset() {
	*x = AlignProgress{}
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignProgress) ProtoMessage() {}

func (x *AlignProgress) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignProgress.ProtoReflect.Descriptor instead.
func (*AlignProgress) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_align_proto_rawDescGZIP(), []int{1}
}

func (x *AlignProgress) GetPct() int32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *AlignProgress) GetEtaS() int32 {
	if x != nil {
		return x.EtaS
	}
	return 0
}

type AlignResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputKey     string                 `protobuf:"bytes,1,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	SegmentCount  int32                  `protobuf:"varint,2,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignResult) Reset() {
	*x = AlignResult{}
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignResult) ProtoMessage() {}

func (x *AlignResult) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignResult.ProtoReflect.Descriptor instead.
func (*AlignResult) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_align_proto_rawDescGZIP(), []int{2}
}

func (x *AlignResult) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *AlignResult) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *AlignResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AlignEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AlignEvent_Progress
	//	*AlignEvent_Result
	Event         isAlignEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignEvent) Reset() {
	*x = AlignEvent{}
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignEvent) ProtoMessage() {}

func (x *AlignEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_align_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignEvent.ProtoReflect.Descriptor instead.
func (*AlignEvent) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_align_proto_rawDescGZIP(), []int{3}
}

func (x *AlignEvent) GetEvent() isAlignEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AlignEvent) GetProgress() *AlignProgress {
	if x != nil {
		if x, ok := x.Event.(*AlignEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *AlignEvent) GetResult() *AlignResult {
	if x != nil {
		if x, ok := x.Event.(*AlignEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isAlignEvent_Event interface {
	isAlignEvent_Event()
}

type AlignEvent_Progress struct {
	Progress *AlignProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type AlignEvent_Result struct {
	Result *AlignResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*AlignEvent_Progress) isAlignEvent_Event() {}

func (*AlignEvent_Result) isAlignEvent_Event() {}

var File_loomtale_worker_v1_align_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_align_proto_rawDesc = "" +
	"\n" +
	"\x1eloomtale/worker/v1/align.proto\x12\x12loomtale.worker.v1\"\x85\x02\n" +
	"\fAlignRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\"\n" +
	"\raudio_get_url\x18\x02 \x01(\tR\vaudioGetUrl\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12$\n" +
	"\x0eoutput_put_url\x18\x04 \x01(\tR\foutputPutUrl\x12D\n" +
	"\x06params\x18\x05 \x03(\v2,.loomtale.worker.v1.AlignRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\rAlignProgress\x12\x10\n" +
	"\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n" +
	"\x05eta_s\x18\x02 \x01(\x05R\x04etaS\"\xd9\x01\n" +
	"\vAlignResult\x12\x1d\n" +
	"\n" +
	"output_key\x18\x01 \x01(\tR\toutputKey\x12#\n" +
	"\rsegment_count\x18\x02 \x01(\x05R\fsegmentCount\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.loomtale.worker.v1.AlignResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\n" +
	"AlignEvent\x12?\n" +
	"\bprogress\x18\x01 \x01(\v2!.loomtale.worker.v1.AlignProgressH\x00R\bprogress\x129\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.loomtale.worker.v1.AlignResultH\x00R\x06resultB\a\n" +
	"\x05event2T\n" +
	"\x05Align\x12K\n" +
	"\x05Align\x12 .loomtale.worker.v1.AlignRequest\x1a\x1e.loomtale.worker.v1.AlignEvent0\x01B<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_align_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_align_proto_rawDescData []byte
)

func file_loomtale_worker_v1_align_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_align_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_align_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_align_proto_rawDesc), len(file_loomtale_worker_v1_align_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_align_proto_rawDescData
}

var file_loomtale_worker_v1_align_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_loomtale_worker_v1_align_proto_goTypes = []any{
	(*AlignRequest)(nil),  // 0: loomtale.worker.v1.AlignRequest
	(*AlignProgress)(nil), // 1: loomtale.worker.v1.AlignProgress
	(*AlignResult)(nil),   // 2: loomtale.worker.v1.AlignResult
	(*AlignEvent)(nil),    // 3: loomtale.worker.v1.AlignEvent
	nil,                   // 4: loomtale.worker.v1.AlignRequest.ParamsEntry
	nil,                   // 5: loomtale.worker.v1.AlignResult.MetadataEntry
}
var file_loomtale_worker_v1_align_proto_depIdxs = []int32{
	4, // 0: loomtale.worker.v1.AlignRequest.params:type_name -> loomtale.worker.v1.AlignRequest.ParamsEntry
	5, // 1: loomtale.worker.v1.AlignResult.metadata:type_name -> loomtale.worker.v1.AlignResult.MetadataEntry
	1, // 2: loomtale.worker.v1.AlignEvent.progress:type_name -> loomtale.worker.v1.AlignProgress
	2, // 3: loomtale.worker.v1.AlignEvent.result:type_name -> loomtale.worker.v1.AlignResult
	0, // 4: loomtale.worker.v1.Align.Align:input_type -> loomtale.worker.v1.AlignRequest
	3, // 5: loomtale.worker.v1.Align.Align:output_type -> loomtale.worker.v1.AlignEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_align_proto_init() }
func file_loomtale_worker_v1_align_proto_init() {
	if File_loomtale_worker_v1_align_proto != nil {
		return
	}
	file_loomtale_worker_v1_align_proto_msgTypes[3].OneofWrappers = []any{
		(*AlignEvent_Progress)(nil),
		(*AlignEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_align_proto_rawDesc), len(file_loomtale_worker_v1_align_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_align_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_align_proto_depIdxs,
		MessageInfos:      file_loomtale_worker_v1_align_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_align_proto = out.File
	file_loomtale_worker_v1_align_proto_goTypes = nil
	file_loomtale_worker_v1_align_proto_depIdxs = nil
}
