// Forced-alignment RPC: aligns narration text to an existing audio asset
// and produces a timed-segment output (e.g. for subtitle/caption assets).
// Same presigned-URL contract as tts.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loomtale/worker/v1/align.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Align_Align_FullMethodName = "/loomtale.worker.v1.Align/Align"
)

// AlignClient is the client API for Align service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlignClient interface {
	Align(ctx context.Context, in *AlignRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlignEvent], error)
}

type alignClient struct {
	cc grpc.ClientConnInterface
}

func NewAlignClient(cc grpc.ClientConnInterface) AlignClient {
	return &alignClient{cc}
}

func (c *alignClient) Align(ctx context.Context, in *AlignRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlignEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Align_ServiceDesc.Streams[0], Align_Align_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AlignRequest, AlignEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Align_AlignClient = grpc.ServerStreamingClient[AlignEvent]

// AlignServer is the server API for Align service.
// All implementations must embed UnimplementedAlignServer
// for forward compatibility.
type AlignServer interface {
	Align(*AlignRequest, grpc.ServerStreamingServer[AlignEvent]) error
	mustEmbedUnimplementedAlignServer()
}

// UnimplementedAlignServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlignServer struct{}

func (UnimplementedAlignServer) Align(*AlignRequest, grpc.ServerStreamingServer[AlignEvent]) error {
	return status.Error(codes.Unimplemented, "method Align not implemented")
}
func (UnimplementedAlignServer) mustEmbedUnimplementedAlignServer() {}
func (UnimplementedAlignServer) testEmbeddedByValue()               {}

// UnsafeAlignServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlignServer will
// result in compilation errors.
type UnsafeAlignServer interface {
	mustEmbedUnimplementedAlignServer()
}

func RegisterAlignServer(s grpc.ServiceRegistrar, srv AlignServer) {
	// If the following call panics, it indicates UnimplementedAlignServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Align_ServiceDesc, srv)
}

func _Align_Align_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AlignRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlignServer).Align(m, &grpc.GenericServerStream[AlignRequest, AlignEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Align_AlignServer = grpc.ServerStreamingServer[AlignEvent]

// Align_ServiceDesc is the grpc.ServiceDesc for Align service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Align_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomtale.worker.v1.Align",
	HandlerType: (*AlignServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Align",
			Handler:       _Align_Align_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loomtale/worker/v1/align.proto",
}
