// Health service exposed by every Python worker so the Go side can probe
// readiness over the same gRPC contract used for real jobs. This proves the
// one-toolchain buf pipeline (Go stubs + Python stubs from a single
// `buf generate`) before any real worker RPC is added in phase 4.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loomtale/worker/v1/health.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerHealth_Check_FullMethodName = "/loomtale.worker.v1.WorkerHealth/Check"
)

// WorkerHealthClient is the client API for WorkerHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerHealth reports liveness for a Python GPU/CPU worker process.
type WorkerHealthClient interface {
	// Check returns the worker's current status.
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type workerHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerHealthClient(cc grpc.ClientConnInterface) WorkerHealthClient {
	return &workerHealthClient{cc}
}

func (c *workerHealthClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WorkerHealth_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerHealthServer is the server API for WorkerHealth service.
// All implementations must embed UnimplementedWorkerHealthServer
// for forward compatibility.
//
// WorkerHealth reports liveness for a Python GPU/CPU worker process.
type WorkerHealthServer interface {
	// Check returns the worker's current status.
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedWorkerHealthServer()
}

// UnimplementedWorkerHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerHealthServer struct{}

func (UnimplementedWorkerHealthServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedWorkerHealthServer) mustEmbedUnimplementedWorkerHealthServer() {}
func (UnimplementedWorkerHealthServer) testEmbeddedByValue()                      {}

// UnsafeWorkerHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerHealthServer will
// result in compilation errors.
type UnsafeWorkerHealthServer interface {
	mustEmbedUnimplementedWorkerHealthServer()
}

func RegisterWorkerHealthServer(s grpc.ServiceRegistrar, srv WorkerHealthServer) {
	// If the following call panics, it indicates UnimplementedWorkerHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerHealth_ServiceDesc, srv)
}

func _WorkerHealth_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerHealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerHealth_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerHealthServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerHealth_ServiceDesc is the grpc.ServiceDesc for WorkerHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomtale.worker.v1.WorkerHealth",
	HandlerType: (*WorkerHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _WorkerHealth_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loomtale/worker/v1/health.proto",
}
