// Health service exposed by every Python worker so the Go side can probe
// readiness over the same gRPC contract used for real jobs. This proves the
// one-toolchain buf pipeline (Go stubs + Python stubs from a single
// `buf generate`) before any real worker RPC is added in phase 4.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/health.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_STATUS_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_STATUS_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_STATUS_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_SERVING",
		2: "STATUS_NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"STATUS_UNKNOWN":     0,
		"STATUS_SERVING":     1,
		"STATUS_NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_loomtale_worker_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_loomtale_worker_v1_health_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_health_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional service name to scope the check; empty means the whole process.
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_loomtale_worker_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=loomtale.worker.v1.HealthCheckResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_loomtale_worker_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_STATUS_UNKNOWN
}

var File_loomtale_worker_v1_health_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1floomtale/worker/v1/health.proto\x12\x12loomtale.worker.v1\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xa7\x01\n" +
	"\x13HealthCheckResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..loomtale.worker.v1.HealthCheckResponse.StatusR\x06status\"H\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x022h\n" +
	"\fWorkerHealth\x12X\n" +
	"\x05Check\x12&.loomtale.worker.v1.HealthCheckRequest\x1a'.loomtale.worker.v1.HealthCheckResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_health_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_health_proto_rawDescData []byte
)

func file_loomtale_worker_v1_health_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_health_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_health_proto_rawDesc), len(file_loomtale_worker_v1_health_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_health_proto_rawDescData
}

var file_loomtale_worker_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loomtale_worker_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loomtale_worker_v1_health_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: loomtale.worker.v1.HealthCheckResponse.Status
	(*HealthCheckRequest)(nil),      // 1: loomtale.worker.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 2: loomtale.worker.v1.HealthCheckResponse
}
var file_loomtale_worker_v1_health_proto_depIdxs = []int32{
	0, // 0: loomtale.worker.v1.HealthCheckResponse.status:type_name -> loomtale.worker.v1.HealthCheckResponse.Status
	1, // 1: loomtale.worker.v1.WorkerHealth.Check:input_type -> loomtale.worker.v1.HealthCheckRequest
	2, // 2: loomtale.worker.v1.WorkerHealth.Check:output_type -> loomtale.worker.v1.HealthCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_health_proto_init() }
func file_loomtale_worker_v1_health_proto_init() {
	if File_loomtale_worker_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_health_proto_rawDesc), len(file_loomtale_worker_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_health_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_health_proto_depIdxs,
		EnumInfos:         file_loomtale_worker_v1_health_proto_enumTypes,
		MessageInfos:      file_loomtale_worker_v1_health_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_health_proto = out.File
	file_loomtale_worker_v1_health_proto_goTypes = nil
	file_loomtale_worker_v1_health_proto_depIdxs = nil
}
