// Fine-tuning/LoRA training RPC (the ai-toolkit engine arrives in phase
// 9c). Streams progress and log lines separately from the final result so
// a caller can show a live log tail without polling.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/train.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	BaseModel     string                 `protobuf:"bytes,2,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	DatasetGetUrl string                 `protobuf:"bytes,3,opt,name=dataset_get_url,json=datasetGetUrl,proto3" json:"dataset_get_url,omitempty"` // presigned GET for the training dataset archive
	OutputPutUrl  string                 `protobuf:"bytes,4,opt,name=output_put_url,json=outputPutUrl,proto3" json:"output_put_url,omitempty"`    // presigned PUT for the resulting weights archive
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_train_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TrainRequest) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *TrainRequest) GetDatasetGetUrl() string {
	if x != nil {
		return x.DatasetGetUrl
	}
	return ""
}

func (x *TrainRequest) GetOutputPutUrl() string {
	if x != nil {
		return x.OutputPutUrl
	}
	return ""
}

func (x *TrainRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type TrainProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pct           int32                  `protobuf:"varint,1,opt,name=pct,proto3" json:"pct,omitempty"`
	EtaS          int32                  `protobuf:"varint,2,opt,name=eta_s,json=etaS,proto3" json:"eta_s,omitempty"`
	Step          int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainProgress) Reset() {
	*x = TrainProgress{}
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainProgress) ProtoMessage() {}

func (x *TrainProgress) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainProgress.ProtoReflect.Descriptor instead.
func (*TrainProgress) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_train_proto_rawDescGZIP(), []int{1}
}

func (x *TrainProgress) GetPct() int32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *TrainProgress) GetEtaS() int32 {
	if x != nil {
		return x.EtaS
	}
	return 0
}

func (x *TrainProgress) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TrainProgress) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

type TrainLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainLog) Reset() {
	*x = TrainLog{}
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainLog) ProtoMessage() {}

func (x *TrainLog) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainLog.ProtoReflect.Descriptor instead.
func (*TrainLog) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_train_proto_rawDescGZIP(), []int{2}
}

func (x *TrainLog) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type TrainResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputKey     string                 `protobuf:"bytes,1,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResult) Reset() {
	*x = TrainResult{}
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResult) ProtoMessage() {}

func (x *TrainResult) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResult.ProtoReflect.Descriptor instead.
func (*TrainResult) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_train_proto_rawDescGZIP(), []int{3}
}

func (x *TrainResult) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *TrainResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TrainEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*TrainEvent_Progress
	//	*TrainEvent_Log
	//	*TrainEvent_Result
	Event         isTrainEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainEvent) Reset() {
	*x = TrainEvent{}
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainEvent) ProtoMessage() {}

func (x *TrainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_train_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainEvent.ProtoReflect.Descriptor instead.
func (*TrainEvent) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_train_proto_rawDescGZIP(), []int{4}
}

func (x *TrainEvent) GetEvent() isTrainEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TrainEvent) GetProgress() *TrainProgress {
	if x != nil {
		if x, ok := x.Event.(*TrainEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TrainEvent) GetLog() *TrainLog {
	if x != nil {
		if x, ok := x.Event.(*TrainEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *TrainEvent) GetResult() *TrainResult {
	if x != nil {
		if x, ok := x.Event.(*TrainEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isTrainEvent_Event interface {
	isTrainEvent_Event()
}

type TrainEvent_Progress struct {
	Progress *TrainProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type TrainEvent_Log struct {
	Log *TrainLog `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type TrainEvent_Result struct {
	Result *TrainResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*TrainEvent_Progress) isTrainEvent_Event() {}

func (*TrainEvent_Log) isTrainEvent_Event() {}

func (*TrainEvent_Result) isTrainEvent_Event() {}

var File_loomtale_worker_v1_train_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_train_proto_rawDesc = "" +
	"\n" +
	"\x1eloomtale/worker/v1/train.proto\x12\x12loomtale.worker.v1\"\x94\x02\n" +
	"\fTrainRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x1d\n" +
	"\n" +
	"base_model\x18\x02 \x01(\tR\tbaseModel\x12&\n" +
	"\x0fdataset_get_url\x18\x03 \x01(\tR\rdatasetGetUrl\x12$\n" +
	"\x0eoutput_put_url\x18\x04 \x01(\tR\foutputPutUrl\x12D\n" +
	"\x06params\x18\x05 \x03(\v2,.loomtale.worker.v1.TrainRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\rTrainProgress\x12\x10\n" +
	"\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n" +
	"\x05eta_s\x18\x02 \x01(\x05R\x04etaS\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\"\x1e\n" +
	"\bTrainLog\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"\xb4\x01\n" +
	"\vTrainResult\x12\x1d\n" +
	"\n" +
	"output_key\x18\x01 \x01(\tR\toutputKey\x12I\n" +
	"\bmetadata\x18\x02 \x03(\v2-.loomtale.worker.v1.TrainResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\n" +
	"TrainEvent\x12?\n" +
	"\bprogress\x18\x01 \x01(\v2!.loomtale.worker.v1.TrainProgressH\x00R\bprogress\x120\n" +
	"\x03log\x18\x02 \x01(\v2\x1c.loomtale.worker.v1.TrainLogH\x00R\x03log\x129\n" +
	"\x06result\x18\x03 \x01(\v2\x1f.loomtale.worker.v1.TrainResultH\x00R\x06resultB\a\n" +
	"\x05event2T\n" +
	"\x05Train\x12K\n" +
	"\x05Train\x12 .loomtale.worker.v1.TrainRequest\x1a\x1e.loomtale.worker.v1.TrainEvent0\x01B<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_train_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_train_proto_rawDescData []byte
)

func file_loomtale_worker_v1_train_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_train_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_train_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_train_proto_rawDesc), len(file_loomtale_worker_v1_train_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_train_proto_rawDescData
}

var file_loomtale_worker_v1_train_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_loomtale_worker_v1_train_proto_goTypes = []any{
	(*TrainRequest)(nil),  // 0: loomtale.worker.v1.TrainRequest
	(*TrainProgress)(nil), // 1: loomtale.worker.v1.TrainProgress
	(*TrainLog)(nil),      // 2: loomtale.worker.v1.TrainLog
	(*TrainResult)(nil),   // 3: loomtale.worker.v1.TrainResult
	(*TrainEvent)(nil),    // 4: loomtale.worker.v1.TrainEvent
	nil,                   // 5: loomtale.worker.v1.TrainRequest.ParamsEntry
	nil,                   // 6: loomtale.worker.v1.TrainResult.MetadataEntry
}
var file_loomtale_worker_v1_train_proto_depIdxs = []int32{
	5, // 0: loomtale.worker.v1.TrainRequest.params:type_name -> loomtale.worker.v1.TrainRequest.ParamsEntry
	6, // 1: loomtale.worker.v1.TrainResult.metadata:type_name -> loomtale.worker.v1.TrainResult.MetadataEntry
	1, // 2: loomtale.worker.v1.TrainEvent.progress:type_name -> loomtale.worker.v1.TrainProgress
	2, // 3: loomtale.worker.v1.TrainEvent.log:type_name -> loomtale.worker.v1.TrainLog
	3, // 4: loomtale.worker.v1.TrainEvent.result:type_name -> loomtale.worker.v1.TrainResult
	0, // 5: loomtale.worker.v1.Train.Train:input_type -> loomtale.worker.v1.TrainRequest
	4, // 6: loomtale.worker.v1.Train.Train:output_type -> loomtale.worker.v1.TrainEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_train_proto_init() }
func file_loomtale_worker_v1_train_proto_init() {
	if File_loomtale_worker_v1_train_proto != nil {
		return
	}
	file_loomtale_worker_v1_train_proto_msgTypes[4].OneofWrappers = []any{
		(*TrainEvent_Progress)(nil),
		(*TrainEvent_Log)(nil),
		(*TrainEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_train_proto_rawDesc), len(file_loomtale_worker_v1_train_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_train_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_train_proto_depIdxs,
		MessageInfos:      file_loomtale_worker_v1_train_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_train_proto = out.File
	file_loomtale_worker_v1_train_proto_goTypes = nil
	file_loomtale_worker_v1_train_proto_depIdxs = nil
}
