// Fine-tuning/LoRA training RPC (the ai-toolkit engine arrives in phase
// 9c). Streams progress and log lines separately from the final result so
// a caller can show a live log tail without polling.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loomtale/worker/v1/train.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Train_Train_FullMethodName = "/loomtale.worker.v1.Train/Train"
)

// TrainClient is the client API for Train service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainClient interface {
	Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainEvent], error)
}

type trainClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainClient(cc grpc.ClientConnInterface) TrainClient {
	return &trainClient{cc}
}

func (c *trainClient) Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrainEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Train_ServiceDesc.Streams[0], Train_Train_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrainRequest, TrainEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Train_TrainClient = grpc.ServerStreamingClient[TrainEvent]

// TrainServer is the server API for Train service.
// All implementations must embed UnimplementedTrainServer
// for forward compatibility.
type TrainServer interface {
	Train(*TrainRequest, grpc.ServerStreamingServer[TrainEvent]) error
	mustEmbedUnimplementedTrainServer()
}

// UnimplementedTrainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainServer struct{}

func (UnimplementedTrainServer) Train(*TrainRequest, grpc.ServerStreamingServer[TrainEvent]) error {
	return status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedTrainServer) mustEmbedUnimplementedTrainServer() {}
func (UnimplementedTrainServer) testEmbeddedByValue()               {}

// UnsafeTrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainServer will
// result in compilation errors.
type UnsafeTrainServer interface {
	mustEmbedUnimplementedTrainServer()
}

func RegisterTrainServer(s grpc.ServiceRegistrar, srv TrainServer) {
	// If the following call panics, it indicates UnimplementedTrainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Train_ServiceDesc, srv)
}

func _Train_Train_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TrainServer).Train(m, &grpc.GenericServerStream[TrainRequest, TrainEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Train_TrainServer = grpc.ServerStreamingServer[TrainEvent]

// Train_ServiceDesc is the grpc.ServiceDesc for Train service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Train_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomtale.worker.v1.Train",
	HandlerType: (*TrainServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Train",
			Handler:       _Train_Train_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loomtale/worker/v1/train.proto",
}
