// Text-to-speech RPC. Inputs and outputs never travel as message bytes:
// the caller passes internal presigned URLs (api/internal/storage.Internal,
// step-length TTL) so the worker holds no S3 credentials and the 4MB gRPC
// message cap only has to cover text/metadata, never audio.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/tts.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	OutputPutUrl  string                 `protobuf:"bytes,4,opt,name=output_put_url,json=outputPutUrl,proto3" json:"output_put_url,omitempty"` // presigned PUT for the resulting audio asset
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_tts_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SynthesizeRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetOutputPutUrl() string {
	if x != nil {
		return x.OutputPutUrl
	}
	return ""
}

func (x *SynthesizeRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SynthesizeProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pct           int32                  `protobuf:"varint,1,opt,name=pct,proto3" json:"pct,omitempty"`
	EtaS          int32                  `protobuf:"varint,2,opt,name=eta_s,json=etaS,proto3" json:"eta_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeProgress) Reset() {
	*x = SynthesizeProgress{}
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeProgress) ProtoMessage() {}

func (x *SynthesizeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeProgress.ProtoReflect.Descriptor instead.
func (*SynthesizeProgress) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_tts_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesizeProgress) GetPct() int32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *SynthesizeProgress) GetEtaS() int32 {
	if x != nil {
		return x.EtaS
	}
	return 0
}

type SynthesizeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputKey     string                 `protobuf:"bytes,1,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	DurationS     float64                `protobuf:"fixed64,2,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResult) Reset() {
	*x = SynthesizeResult{}
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResult) ProtoMessage() {}

func (x *SynthesizeResult) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResult.ProtoReflect.Descriptor instead.
func (*SynthesizeResult) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_tts_proto_rawDescGZIP(), []int{2}
}

func (x *SynthesizeResult) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *SynthesizeResult) GetDurationS() float64 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *SynthesizeResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SynthesizeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SynthesizeEvent_Progress
	//	*SynthesizeEvent_Result
	Event         isSynthesizeEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeEvent) Reset() {
	*x = SynthesizeEvent{}
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeEvent) ProtoMessage() {}

func (x *SynthesizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeEvent.ProtoReflect.Descriptor instead.
func (*SynthesizeEvent) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_tts_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesizeEvent) GetEvent() isSynthesizeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SynthesizeEvent) GetProgress() *SynthesizeProgress {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *SynthesizeEvent) GetResult() *SynthesizeResult {
	if x != nil {
		if x, ok := x.Event.(*SynthesizeEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isSynthesizeEvent_Event interface {
	isSynthesizeEvent_Event()
}

type SynthesizeEvent_Progress struct {
	Progress *SynthesizeProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type SynthesizeEvent_Result struct {
	Result *SynthesizeResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*SynthesizeEvent_Progress) isSynthesizeEvent_Event() {}

func (*SynthesizeEvent_Result) isSynthesizeEvent_Event() {}

var File_loomtale_worker_v1_tts_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_tts_proto_rawDesc = "" +
	"\n" +
	"\x1cloomtale/worker/v1/tts.proto\x12\x12loomtale.worker.v1\"\x81\x02\n" +
	"\x11SynthesizeRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12$\n" +
	"\x0eoutput_put_url\x18\x04 \x01(\tR\foutputPutUrl\x12I\n" +
	"\x06params\x18\x05 \x03(\v21.loomtale.worker.v1.SynthesizeRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x12SynthesizeProgress\x12\x10\n" +
	"\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n" +
	"\x05eta_s\x18\x02 \x01(\x05R\x04etaS\"\xdd\x01\n" +
	"\x10SynthesizeResult\x12\x1d\n" +
	"\n" +
	"output_key\x18\x01 \x01(\tR\toutputKey\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x02 \x01(\x01R\tdurationS\x12N\n" +
	"\bmetadata\x18\x03 \x03(\v22.loomtale.worker.v1.SynthesizeResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x0fSynthesizeEvent\x12D\n" +
	"\bprogress\x18\x01 \x01(\v2&.loomtale.worker.v1.SynthesizeProgressH\x00R\bprogress\x12>\n" +
	"\x06result\x18\x02 \x01(\v2$.loomtale.worker.v1.SynthesizeResultH\x00R\x06resultB\a\n" +
	"\x05event2a\n" +
	"\x03TTS\x12Z\n" +
	"\n" +
	"Synthesize\x12%.loomtale.worker.v1.SynthesizeRequest\x1a#.loomtale.worker.v1.SynthesizeEvent0\x01B<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_tts_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_tts_proto_rawDescData []byte
)

func file_loomtale_worker_v1_tts_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_tts_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_tts_proto_rawDesc), len(file_loomtale_worker_v1_tts_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_tts_proto_rawDescData
}

var file_loomtale_worker_v1_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_loomtale_worker_v1_tts_proto_goTypes = []any{
	(*SynthesizeRequest)(nil),  // 0: loomtale.worker.v1.SynthesizeRequest
	(*SynthesizeProgress)(nil), // 1: loomtale.worker.v1.SynthesizeProgress
	(*SynthesizeResult)(nil),   // 2: loomtale.worker.v1.SynthesizeResult
	(*SynthesizeEvent)(nil),    // 3: loomtale.worker.v1.SynthesizeEvent
	nil,                        // 4: loomtale.worker.v1.SynthesizeRequest.ParamsEntry
	nil,                        // 5: loomtale.worker.v1.SynthesizeResult.MetadataEntry
}
var file_loomtale_worker_v1_tts_proto_depIdxs = []int32{
	4, // 0: loomtale.worker.v1.SynthesizeRequest.params:type_name -> loomtale.worker.v1.SynthesizeRequest.ParamsEntry
	5, // 1: loomtale.worker.v1.SynthesizeResult.metadata:type_name -> loomtale.worker.v1.SynthesizeResult.MetadataEntry
	1, // 2: loomtale.worker.v1.SynthesizeEvent.progress:type_name -> loomtale.worker.v1.SynthesizeProgress
	2, // 3: loomtale.worker.v1.SynthesizeEvent.result:type_name -> loomtale.worker.v1.SynthesizeResult
	0, // 4: loomtale.worker.v1.TTS.Synthesize:input_type -> loomtale.worker.v1.SynthesizeRequest
	3, // 5: loomtale.worker.v1.TTS.Synthesize:output_type -> loomtale.worker.v1.SynthesizeEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_tts_proto_init() }
func file_loomtale_worker_v1_tts_proto_init() {
	if File_loomtale_worker_v1_tts_proto != nil {
		return
	}
	file_loomtale_worker_v1_tts_proto_msgTypes[3].OneofWrappers = []any{
		(*SynthesizeEvent_Progress)(nil),
		(*SynthesizeEvent_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_tts_proto_rawDesc), len(file_loomtale_worker_v1_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_tts_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_tts_proto_depIdxs,
		MessageInfos:      file_loomtale_worker_v1_tts_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_tts_proto = out.File
	file_loomtale_worker_v1_tts_proto_goTypes = nil
	file_loomtale_worker_v1_tts_proto_depIdxs = nil
}
