// Text-to-speech RPC. Inputs and outputs never travel as message bytes:
// the caller passes internal presigned URLs (api/internal/storage.Internal,
// step-length TTL) so the worker holds no S3 credentials and the 4MB gRPC
// message cap only has to cover text/metadata, never audio.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loomtale/worker/v1/tts.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTS_Synthesize_FullMethodName = "/loomtale.worker.v1.TTS/Synthesize"
)

// TTSClient is the client API for TTS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSClient interface {
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesizeEvent], error)
}

type tTSClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSClient(cc grpc.ClientConnInterface) TTSClient {
	return &tTSClient{cc}
}

func (c *tTSClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesizeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTS_ServiceDesc.Streams[0], TTS_Synthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeRequest, SynthesizeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTS_SynthesizeClient = grpc.ServerStreamingClient[SynthesizeEvent]

// TTSServer is the server API for TTS service.
// All implementations must embed UnimplementedTTSServer
// for forward compatibility.
type TTSServer interface {
	Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[SynthesizeEvent]) error
	mustEmbedUnimplementedTTSServer()
}

// UnimplementedTTSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServer struct{}

func (UnimplementedTTSServer) Synthesize(*SynthesizeRequest, grpc.ServerStreamingServer[SynthesizeEvent]) error {
	return status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedTTSServer) mustEmbedUnimplementedTTSServer() {}
func (UnimplementedTTSServer) testEmbeddedByValue()             {}

// UnsafeTTSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServer will
// result in compilation errors.
type UnsafeTTSServer interface {
	mustEmbedUnimplementedTTSServer()
}

func RegisterTTSServer(s grpc.ServiceRegistrar, srv TTSServer) {
	// If the following call panics, it indicates UnimplementedTTSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTS_ServiceDesc, srv)
}

func _TTS_Synthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServer).Synthesize(m, &grpc.GenericServerStream[SynthesizeRequest, SynthesizeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTS_SynthesizeServer = grpc.ServerStreamingServer[SynthesizeEvent]

// TTS_ServiceDesc is the grpc.ServiceDesc for TTS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomtale.worker.v1.TTS",
	HandlerType: (*TTSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Synthesize",
			Handler:       _TTS_Synthesize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loomtale/worker/v1/tts.proto",
}
