// Vision-model RPCs (LoRA/render scoring and depth extraction, phase 9c
// engines): both are short unary calls, unlike the streaming media RPCs
// above, since their outputs are a single small value or a single asset.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loomtale/worker/v1/vision.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vision_Score_FullMethodName = "/loomtale.worker.v1.Vision/Score"
	Vision_Depth_FullMethodName = "/loomtale.worker.v1.Vision/Depth"
)

// VisionClient is the client API for Vision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisionClient interface {
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
	Depth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (*DepthResponse, error)
}

type visionClient struct {
	cc grpc.ClientConnInterface
}

func NewVisionClient(cc grpc.ClientConnInterface) VisionClient {
	return &visionClient{cc}
}

func (c *visionClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, Vision_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visionClient) Depth(ctx context.Context, in *DepthRequest, opts ...grpc.CallOption) (*DepthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepthResponse)
	err := c.cc.Invoke(ctx, Vision_Depth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisionServer is the server API for Vision service.
// All implementations must embed UnimplementedVisionServer
// for forward compatibility.
type VisionServer interface {
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	Depth(context.Context, *DepthRequest) (*DepthResponse, error)
	mustEmbedUnimplementedVisionServer()
}

// UnimplementedVisionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisionServer struct{}

func (UnimplementedVisionServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedVisionServer) Depth(context.Context, *DepthRequest) (*DepthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Depth not implemented")
}
func (UnimplementedVisionServer) mustEmbedUnimplementedVisionServer() {}
func (UnimplementedVisionServer) testEmbeddedByValue()                {}

// UnsafeVisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisionServer will
// result in compilation errors.
type UnsafeVisionServer interface {
	mustEmbedUnimplementedVisionServer()
}

func RegisterVisionServer(s grpc.ServiceRegistrar, srv VisionServer) {
	// If the following call panics, it indicates UnimplementedVisionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vision_ServiceDesc, srv)
}

func _Vision_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vision_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vision_Depth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisionServer).Depth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vision_Depth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisionServer).Depth(ctx, req.(*DepthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vision_ServiceDesc is the grpc.ServiceDesc for Vision service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vision_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loomtale.worker.v1.Vision",
	HandlerType: (*VisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Score",
			Handler:    _Vision_Score_Handler,
		},
		{
			MethodName: "Depth",
			Handler:    _Vision_Depth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loomtale/worker/v1/vision.proto",
}
