// Vision-model RPCs (LoRA/render scoring and depth extraction, phase 9c
// engines): both are short unary calls, unlike the streaming media RPCs
// above, since their outputs are a single small value or a single asset.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/vision.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	ImageGetUrl   string                 `protobuf:"bytes,2,opt,name=image_get_url,json=imageGetUrl,proto3" json:"image_get_url,omitempty"` // presigned GET for the image to score
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ScoreRequest) GetImageGetUrl() string {
	if x != nil {
		return x.ImageGetUrl
	}
	return ""
}

func (x *ScoreRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	ImageGetUrl   string                 `protobuf:"bytes,2,opt,name=image_get_url,json=imageGetUrl,proto3" json:"image_get_url,omitempty"`
	OutputPutUrl  string                 `protobuf:"bytes,3,opt,name=output_put_url,json=outputPutUrl,proto3" json:"output_put_url,omitempty"` // presigned PUT for the resulting depth map
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthRequest) Reset() {
	*x = DepthRequest{}
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthRequest) ProtoMessage() {}

func (x *DepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthRequest.ProtoReflect.Descriptor instead.
func (*DepthRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_vision_proto_rawDescGZIP(), []int{2}
}

func (x *DepthRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DepthRequest) GetImageGetUrl() string {
	if x != nil {
		return x.ImageGetUrl
	}
	return ""
}

func (x *DepthRequest) GetOutputPutUrl() string {
	if x != nil {
		return x.OutputPutUrl
	}
	return ""
}

func (x *DepthRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type DepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputKey     string                 `protobuf:"bytes,1,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthResponse) Reset() {
	*x = DepthResponse{}
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthResponse) ProtoMessage() {}

func (x *DepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthResponse.ProtoReflect.Descriptor instead.
func (*DepthResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_vision_proto_rawDescGZIP(), []int{3}
}

func (x *DepthResponse) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

var File_loomtale_worker_v1_vision_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x1floomtale/worker/v1/vision.proto\x12\x12loomtale.worker.v1\"\xcb\x01\n" +
	"\fScoreRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\"\n" +
	"\rimage_get_url\x18\x02 \x01(\tR\vimageGetUrl\x12D\n" +
	"\x06params\x18\x03 \x03(\v2,.loomtale.worker.v1.ScoreRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\rScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.loomtale.worker.v1.ScoreResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\fDepthRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\"\n" +
	"\rimage_get_url\x18\x02 \x01(\tR\vimageGetUrl\x12$\n" +
	"\x0eoutput_put_url\x18\x03 \x01(\tR\foutputPutUrl\x12D\n" +
	"\x06params\x18\x04 \x03(\v2,.loomtale.worker.v1.DepthRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\rDepthResponse\x12\x1d\n" +
	"\n" +
	"output_key\x18\x01 \x01(\tR\toutputKey2\xa4\x01\n" +
	"\x06Vision\x12L\n" +
	"\x05Score\x12 .loomtale.worker.v1.ScoreRequest\x1a!.loomtale.worker.v1.ScoreResponse\x12L\n" +
	"\x05Depth\x12 .loomtale.worker.v1.DepthRequest\x1a!.loomtale.worker.v1.DepthResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_vision_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_vision_proto_rawDescData []byte
)

func file_loomtale_worker_v1_vision_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_vision_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_vision_proto_rawDesc), len(file_loomtale_worker_v1_vision_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_vision_proto_rawDescData
}

var file_loomtale_worker_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_loomtale_worker_v1_vision_proto_goTypes = []any{
	(*ScoreRequest)(nil),  // 0: loomtale.worker.v1.ScoreRequest
	(*ScoreResponse)(nil), // 1: loomtale.worker.v1.ScoreResponse
	(*DepthRequest)(nil),  // 2: loomtale.worker.v1.DepthRequest
	(*DepthResponse)(nil), // 3: loomtale.worker.v1.DepthResponse
	nil,                   // 4: loomtale.worker.v1.ScoreRequest.ParamsEntry
	nil,                   // 5: loomtale.worker.v1.ScoreResponse.MetadataEntry
	nil,                   // 6: loomtale.worker.v1.DepthRequest.ParamsEntry
}
var file_loomtale_worker_v1_vision_proto_depIdxs = []int32{
	4, // 0: loomtale.worker.v1.ScoreRequest.params:type_name -> loomtale.worker.v1.ScoreRequest.ParamsEntry
	5, // 1: loomtale.worker.v1.ScoreResponse.metadata:type_name -> loomtale.worker.v1.ScoreResponse.MetadataEntry
	6, // 2: loomtale.worker.v1.DepthRequest.params:type_name -> loomtale.worker.v1.DepthRequest.ParamsEntry
	0, // 3: loomtale.worker.v1.Vision.Score:input_type -> loomtale.worker.v1.ScoreRequest
	2, // 4: loomtale.worker.v1.Vision.Depth:input_type -> loomtale.worker.v1.DepthRequest
	1, // 5: loomtale.worker.v1.Vision.Score:output_type -> loomtale.worker.v1.ScoreResponse
	3, // 6: loomtale.worker.v1.Vision.Depth:output_type -> loomtale.worker.v1.DepthResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_vision_proto_init() }
func file_loomtale_worker_v1_vision_proto_init() {
	if File_loomtale_worker_v1_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_vision_proto_rawDesc), len(file_loomtale_worker_v1_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_vision_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_vision_proto_depIdxs,
		MessageInfos:      file_loomtale_worker_v1_vision_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_vision_proto = out.File
	file_loomtale_worker_v1_vision_proto_goTypes = nil
	file_loomtale_worker_v1_vision_proto_depIdxs = nil
}
