// Control-plane RPCs every Python worker implements regardless of which
// engines it hosts: liveness, engine inventory and residency, and GPU
// memory status. Real engines are registered in phases 9a-9c; before that
// ListEngines returns an empty list and every Load/Unload call fails with
// FAILED_PRECONDITION engine_not_installed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loomtale/worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListEnginesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnginesRequest) Reset() {
	*x = ListEnginesRequest{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnginesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnginesRequest) ProtoMessage() {}

func (x *ListEnginesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnginesRequest.ProtoReflect.Descriptor instead.
func (*ListEnginesRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

type EngineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"` // e.g. "tts", "align", "train", "vision"
	License       string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Installed     bool                   `protobuf:"varint,4,opt,name=installed,proto3" json:"installed,omitempty"` // weights present on disk
	Loaded        bool                   `protobuf:"varint,5,opt,name=loaded,proto3" json:"loaded,omitempty"`
	VramHeldMb    int64                  `protobuf:"varint,6,opt,name=vram_held_mb,json=vramHeldMb,proto3" json:"vram_held_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineInfo) Reset() {
	*x = EngineInfo{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineInfo) ProtoMessage() {}

func (x *EngineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineInfo.ProtoReflect.Descriptor instead.
func (*EngineInfo) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *EngineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EngineInfo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *EngineInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *EngineInfo) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *EngineInfo) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *EngineInfo) GetVramHeldMb() int64 {
	if x != nil {
		return x.VramHeldMb
	}
	return 0
}

type ListEnginesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engines       []*EngineInfo          `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnginesResponse) Reset() {
	*x = ListEnginesResponse{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnginesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnginesResponse) ProtoMessage() {}

func (x *ListEnginesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnginesResponse.ProtoReflect.Descriptor instead.
func (*ListEnginesResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ListEnginesResponse) GetEngines() []*EngineInfo {
	if x != nil {
		return x.Engines
	}
	return nil
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModelRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *LoadModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        bool                   `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	VramHeldMb    int64                  `protobuf:"varint,2,opt,name=vram_held_mb,json=vramHeldMb,proto3" json:"vram_held_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *LoadModelResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *LoadModelResponse) GetVramHeldMb() int64 {
	if x != nil {
		return x.VramHeldMb
	}
	return 0
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *UnloadModelRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unloaded      bool                   `protobuf:"varint,1,opt,name=unloaded,proto3" json:"unloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *UnloadModelResponse) GetUnloaded() bool {
	if x != nil {
		return x.Unloaded
	}
	return false
}

type GpuStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuStatusRequest) Reset() {
	*x = GpuStatusRequest{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuStatusRequest) ProtoMessage() {}

func (x *GpuStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuStatusRequest.ProtoReflect.Descriptor instead.
func (*GpuStatusRequest) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

type GpuStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GpuPresent     bool                   `protobuf:"varint,1,opt,name=gpu_present,json=gpuPresent,proto3" json:"gpu_present,omitempty"`
	TotalMb        int64                  `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	FreeMb         int64                  `protobuf:"varint,3,opt,name=free_mb,json=freeMb,proto3" json:"free_mb,omitempty"`
	ResidentEngine string                 `protobuf:"bytes,4,opt,name=resident_engine,json=residentEngine,proto3" json:"resident_engine,omitempty"` // empty if nothing loaded
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GpuStatusResponse) Reset() {
	*x = GpuStatusResponse{}
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuStatusResponse) ProtoMessage() {}

func (x *GpuStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loomtale_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuStatusResponse.ProtoReflect.Descriptor instead.
func (*GpuStatusResponse) Descriptor() ([]byte, []int) {
	return file_loomtale_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *GpuStatusResponse) GetGpuPresent() bool {
	if x != nil {
		return x.GpuPresent
	}
	return false
}

func (x *GpuStatusResponse) GetTotalMb() int64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *GpuStatusResponse) GetFreeMb() int64 {
	if x != nil {
		return x.FreeMb
	}
	return 0
}

func (x *GpuStatusResponse) GetResidentEngine() string {
	if x != nil {
		return x.ResidentEngine
	}
	return ""
}

var File_loomtale_worker_v1_worker_proto protoreflect.FileDescriptor

const file_loomtale_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1floomtale/worker/v1/worker.proto\x12\x12loomtale.worker.v1\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x14\n" +
	"\x12ListEnginesRequest\"\xa6\x01\n" +
	"\n" +
	"EngineInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12\x1c\n" +
	"\tinstalled\x18\x04 \x01(\bR\tinstalled\x12\x16\n" +
	"\x06loaded\x18\x05 \x01(\bR\x06loaded\x12 \n" +
	"\fvram_held_mb\x18\x06 \x01(\x03R\n" +
	"vramHeldMb\"O\n" +
	"\x13ListEnginesResponse\x128\n" +
	"\aengines\x18\x01 \x03(\v2\x1e.loomtale.worker.v1.EngineInfoR\aengines\"@\n" +
	"\x10LoadModelRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"M\n" +
	"\x11LoadModelResponse\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x12 \n" +
	"\fvram_held_mb\x18\x02 \x01(\x03R\n" +
	"vramHeldMb\",\n" +
	"\x12UnloadModelRequest\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\"1\n" +
	"\x13UnloadModelResponse\x12\x1a\n" +
	"\bunloaded\x18\x01 \x01(\bR\bunloaded\"\x12\n" +
	"\x10GpuStatusRequest\"\x91\x01\n" +
	"\x11GpuStatusResponse\x12\x1f\n" +
	"\vgpu_present\x18\x01 \x01(\bR\n" +
	"gpuPresent\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x03R\atotalMb\x12\x17\n" +
	"\afree_mb\x18\x03 \x01(\x03R\x06freeMb\x12'\n" +
	"\x0fresident_engine\x18\x04 \x01(\tR\x0eresidentEngine2\xcd\x03\n" +
	"\x06Worker\x12O\n" +
	"\x06Health\x12!.loomtale.worker.v1.HealthRequest\x1a\".loomtale.worker.v1.HealthResponse\x12^\n" +
	"\vListEngines\x12&.loomtale.worker.v1.ListEnginesRequest\x1a'.loomtale.worker.v1.ListEnginesResponse\x12X\n" +
	"\tLoadModel\x12$.loomtale.worker.v1.LoadModelRequest\x1a%.loomtale.worker.v1.LoadModelResponse\x12^\n" +
	"\vUnloadModel\x12&.loomtale.worker.v1.UnloadModelRequest\x1a'.loomtale.worker.v1.UnloadModelResponse\x12X\n" +
	"\tGpuStatus\x12$.loomtale.worker.v1.GpuStatusRequest\x1a%.loomtale.worker.v1.GpuStatusResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3"

var (
	file_loomtale_worker_v1_worker_proto_rawDescOnce sync.Once
	file_loomtale_worker_v1_worker_proto_rawDescData []byte
)

func file_loomtale_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_loomtale_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_loomtale_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_worker_proto_rawDesc), len(file_loomtale_worker_v1_worker_proto_rawDesc)))
	})
	return file_loomtale_worker_v1_worker_proto_rawDescData
}

var file_loomtale_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_loomtale_worker_v1_worker_proto_goTypes = []any{
	(*HealthRequest)(nil),       // 0: loomtale.worker.v1.HealthRequest
	(*HealthResponse)(nil),      // 1: loomtale.worker.v1.HealthResponse
	(*ListEnginesRequest)(nil),  // 2: loomtale.worker.v1.ListEnginesRequest
	(*EngineInfo)(nil),          // 3: loomtale.worker.v1.EngineInfo
	(*ListEnginesResponse)(nil), // 4: loomtale.worker.v1.ListEnginesResponse
	(*LoadModelRequest)(nil),    // 5: loomtale.worker.v1.LoadModelRequest
	(*LoadModelResponse)(nil),   // 6: loomtale.worker.v1.LoadModelResponse
	(*UnloadModelRequest)(nil),  // 7: loomtale.worker.v1.UnloadModelRequest
	(*UnloadModelResponse)(nil), // 8: loomtale.worker.v1.UnloadModelResponse
	(*GpuStatusRequest)(nil),    // 9: loomtale.worker.v1.GpuStatusRequest
	(*GpuStatusResponse)(nil),   // 10: loomtale.worker.v1.GpuStatusResponse
}
var file_loomtale_worker_v1_worker_proto_depIdxs = []int32{
	3,  // 0: loomtale.worker.v1.ListEnginesResponse.engines:type_name -> loomtale.worker.v1.EngineInfo
	0,  // 1: loomtale.worker.v1.Worker.Health:input_type -> loomtale.worker.v1.HealthRequest
	2,  // 2: loomtale.worker.v1.Worker.ListEngines:input_type -> loomtale.worker.v1.ListEnginesRequest
	5,  // 3: loomtale.worker.v1.Worker.LoadModel:input_type -> loomtale.worker.v1.LoadModelRequest
	7,  // 4: loomtale.worker.v1.Worker.UnloadModel:input_type -> loomtale.worker.v1.UnloadModelRequest
	9,  // 5: loomtale.worker.v1.Worker.GpuStatus:input_type -> loomtale.worker.v1.GpuStatusRequest
	1,  // 6: loomtale.worker.v1.Worker.Health:output_type -> loomtale.worker.v1.HealthResponse
	4,  // 7: loomtale.worker.v1.Worker.ListEngines:output_type -> loomtale.worker.v1.ListEnginesResponse
	6,  // 8: loomtale.worker.v1.Worker.LoadModel:output_type -> loomtale.worker.v1.LoadModelResponse
	8,  // 9: loomtale.worker.v1.Worker.UnloadModel:output_type -> loomtale.worker.v1.UnloadModelResponse
	10, // 10: loomtale.worker.v1.Worker.GpuStatus:output_type -> loomtale.worker.v1.GpuStatusResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_loomtale_worker_v1_worker_proto_init() }
func file_loomtale_worker_v1_worker_proto_init() {
	if File_loomtale_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loomtale_worker_v1_worker_proto_rawDesc), len(file_loomtale_worker_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loomtale_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_loomtale_worker_v1_worker_proto_depIdxs,
		MessageInfos:      file_loomtale_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_loomtale_worker_v1_worker_proto = out.File
	file_loomtale_worker_v1_worker_proto_goTypes = nil
	file_loomtale_worker_v1_worker_proto_depIdxs = nil
}
