package pipeline

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"

	dbgen "loomtale/api/internal/db/gen"
	"loomtale/api/internal/db/idconv"
)

// StepSpec describes one step to create. ID is generated by the caller
// (uuid.NewV7, matching every other primary key in this codebase) so a
// step can list another step in the same batch as a dependency before
// either is inserted.
type StepSpec struct {
	ID        uuid.UUID
	Kind      string
	ScopeKind string
	ScopeID   uuid.UUID
	Priority  int
	DependsOn []uuid.UUID
	// Input is caller-supplied, handler-specific parameters (e.g. an AI
	// action's selected paragraph ids and free-text instruction), set
	// once at enqueue time and read back via StepContext.Input in Run.
	// Nil is stored as an empty JSON object, never a SQL NULL.
	Input json.RawMessage
}

// RunSpec describes a new pipeline run and its steps.
type RunSpec struct {
	ID        uuid.UUID
	ScopeKind string
	ScopeID   uuid.UUID
	Kind      string
	CreatedBy *uuid.UUID
	Steps     []StepSpec
}

// Enqueue creates a run and its steps in one transaction, runs every
// registered AdmissionCheck first, and inserts a River job for every step
// that has no unmet dependency, chunked to BatchChunkTarget per job. It
// returns the new run id.
//
// spec.Steps' own DependsOn entries must each reference another step in
// the same spec.Steps (checked by validateGraph, which also rejects
// cycles and self-dependencies): Enqueue always creates a wholly new
// run, so there is no existing step in the database a legitimate
// dependency could point at yet.
func (e *Engine) Enqueue(ctx context.Context, tenantID uuid.UUID, spec RunSpec) (uuid.UUID, error) {
	if err := validateGraph(spec.Steps); err != nil {
		return uuid.Nil, err
	}

	tx, err := e.Pool.Begin(ctx)
	if err != nil {
		return uuid.Nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	qtx := e.Queries.WithTx(tx)

	// Serializes concurrent Enqueue calls for the same tenant so the
	// admission checks below (in particular quota.Checker, a
	// check-then-insert) cannot race two calls into both passing.
	if err := qtx.LockTenantForAdmission(ctx, tenantID.String()); err != nil {
		return uuid.Nil, fmt.Errorf("pipeline: lock tenant for admission: %w", err)
	}
	for _, check := range e.Checks {
		if err := check(ctx, qtx, tenantID, len(spec.Steps)); err != nil {
			return uuid.Nil, err
		}
	}

	if _, err := qtx.CreateRun(ctx, dbgen.CreateRunParams{
		ID:        idconv.ToPg(spec.ID),
		TenantID:  idconv.ToPg(tenantID),
		ScopeKind: spec.ScopeKind,
		ScopeID:   idconv.ToPg(spec.ScopeID),
		Kind:      spec.Kind,
		CreatedBy: idconv.ToPgPtr(spec.CreatedBy),
	}); err != nil {
		return uuid.Nil, fmt.Errorf("pipeline: create run: %w", err)
	}

	insertedSteps, err := e.insertSteps(ctx, qtx, tenantID, spec)
	if err != nil {
		return uuid.Nil, err
	}

	if err := e.enqueueReadySteps(ctx, tx, insertedSteps); err != nil {
		return uuid.Nil, fmt.Errorf("pipeline: enqueue ready steps: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return uuid.Nil, err
	}

	for _, s := range insertedSteps {
		publishStepEvent(ctx, e.Pool, s, true)
	}
	return spec.ID, nil
}

func (e *Engine) insertSteps(ctx context.Context, qtx *dbgen.Queries, tenantID uuid.UUID, spec RunSpec) ([]dbgen.PipelineStep, error) {
	type resolvedStep struct {
		spec        StepSpec
		queue       string
		hash        string
		providerRef string
	}
	resolved := make([]resolvedStep, len(spec.Steps))
	for i, s := range spec.Steps {
		h, ok := e.Registry.Lookup(s.Kind)
		if !ok {
			return nil, fmt.Errorf("%w: %q", ErrUnknownStepKind, s.Kind)
		}
		ref := StepRef{ID: s.ID, TenantID: tenantID, RunID: spec.ID, ScopeKind: s.ScopeKind, ScopeID: s.ScopeID, Kind: s.Kind, Input: s.Input}
		queue, err := h.Queue(ctx, ref)
		if err != nil {
			return nil, fmt.Errorf("pipeline: resolve queue for step %s: %w", s.ID, err)
		}
		hash, err := h.InputHash(ctx, ref)
		if err != nil {
			return nil, fmt.Errorf("pipeline: compute input hash for step %s: %w", s.ID, err)
		}
		var providerRef string
		if model, err := h.ModelRef(ctx, ref); err != nil {
			return nil, fmt.Errorf("pipeline: resolve model ref for step %s: %w", s.ID, err)
		} else if model != nil {
			providerRef = model.Backend + ":" + model.Model
		}
		resolved[i] = resolvedStep{spec: s, queue: queue, hash: hash, providerRef: providerRef}
	}

	params := make([]dbgen.InsertStepBatchParams, len(resolved))
	for i, r := range resolved {
		status := StatusPending
		if len(r.spec.DependsOn) == 0 {
			status = StatusQueued
		}
		input := r.spec.Input
		if len(input) == 0 {
			input = json.RawMessage("{}")
		}
		params[i] = dbgen.InsertStepBatchParams{
			ID:            idconv.ToPg(r.spec.ID),
			TenantID:      idconv.ToPg(tenantID),
			RunID:         idconv.ToPg(spec.ID),
			ScopeKind:     r.spec.ScopeKind,
			ScopeID:       idconv.ToPg(r.spec.ScopeID),
			Kind:          r.spec.Kind,
			Queue:         r.queue,
			ProviderRef:   r.providerRef,
			Priority:      int16(r.spec.Priority),
			Status:        status,
			RemainingDeps: int32(len(r.spec.DependsOn)),
			InputHash:     r.hash,
			Input:         input,
		}
	}

	steps := make([]dbgen.PipelineStep, 0, len(params))
	var firstErr error
	if len(params) > 0 {
		qtx.InsertStepBatch(ctx, params).QueryRow(func(_ int, step dbgen.PipelineStep, err error) {
			if err != nil {
				if firstErr == nil {
					firstErr = err
				}
				return
			}
			steps = append(steps, step)
		})
		if firstErr != nil {
			return nil, fmt.Errorf("pipeline: insert steps: %w", firstErr)
		}
	}

	var depParams []dbgen.InsertStepDepBatchParams
	for _, r := range resolved {
		for _, dep := range r.spec.DependsOn {
			depParams = append(depParams, dbgen.InsertStepDepBatchParams{
				TenantID:        idconv.ToPg(tenantID),
				StepID:          idconv.ToPg(r.spec.ID),
				DependsOnStepID: idconv.ToPg(dep),
			})
		}
	}
	if len(depParams) > 0 {
		var depErr error
		qtx.InsertStepDepBatch(ctx, depParams).Exec(func(_ int, err error) {
			if err != nil && depErr == nil {
				depErr = err
			}
		})
		if depErr != nil {
			return nil, fmt.Errorf("pipeline: insert step deps: %w", depErr)
		}
	}

	return steps, nil
}
