package pipeline

import (
	"context"
	"fmt"
	"sort"

	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"

	dbgen "loomtale/api/internal/db/gen"
	"loomtale/api/internal/db/idconv"
)

// StepSpec describes one step to create. ID is generated by the caller
// (uuid.NewV7, matching every other primary key in this codebase) so a
// step can list another step in the same batch as a dependency before
// either is inserted.
type StepSpec struct {
	ID        uuid.UUID
	Kind      string
	ScopeKind string
	ScopeID   uuid.UUID
	Priority  int
	DependsOn []uuid.UUID
}

// RunSpec describes a new pipeline run and its steps.
type RunSpec struct {
	ID        uuid.UUID
	ScopeKind string
	ScopeID   uuid.UUID
	Kind      string
	CreatedBy *uuid.UUID
	Steps     []StepSpec
}

// readyUniqueStates is the set of River job states in which a duplicate
// insert for the same step set must be rejected: a step already
// available, scheduled, running or retryable already has a live job, so
// the reconciler's ready-sweep and River's own stuck-job rescue can both
// try to enqueue the same step without ever double-queuing it.
var readyUniqueStates = []rivertype.JobState{
	rivertype.JobStateAvailable,
	rivertype.JobStateScheduled,
	rivertype.JobStateRunning,
	rivertype.JobStateRetryable,
	rivertype.JobStatePending,
}

// Enqueue creates a run and its steps in one transaction, runs every
// registered AdmissionCheck first, and inserts a River job for every step
// that has no unmet dependency, chunked to BatchChunkTarget per job. It
// returns the new run id.
func (e *Engine) Enqueue(ctx context.Context, tenantID uuid.UUID, spec RunSpec) (uuid.UUID, error) {
	for _, check := range e.Checks {
		if err := check(ctx, tenantID, len(spec.Steps)); err != nil {
			return uuid.Nil, err
		}
	}

	tx, err := e.Pool.Begin(ctx)
	if err != nil {
		return uuid.Nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	qtx := e.Queries.WithTx(tx)

	if _, err := qtx.CreateRun(ctx, dbgen.CreateRunParams{
		ID:        idconv.ToPg(spec.ID),
		TenantID:  idconv.ToPg(tenantID),
		ScopeKind: spec.ScopeKind,
		ScopeID:   idconv.ToPg(spec.ScopeID),
		Kind:      spec.Kind,
		CreatedBy: idconv.ToPgPtr(spec.CreatedBy),
	}); err != nil {
		return uuid.Nil, fmt.Errorf("pipeline: create run: %w", err)
	}

	insertedSteps, err := e.insertSteps(ctx, qtx, tenantID, spec)
	if err != nil {
		return uuid.Nil, err
	}

	if err := e.enqueueReadySteps(ctx, tx, insertedSteps); err != nil {
		return uuid.Nil, fmt.Errorf("pipeline: enqueue ready steps: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return uuid.Nil, err
	}

	for _, s := range insertedSteps {
		publishStepEvent(ctx, e.Pool, s, true)
	}
	return spec.ID, nil
}

func (e *Engine) insertSteps(ctx context.Context, qtx *dbgen.Queries, tenantID uuid.UUID, spec RunSpec) ([]dbgen.PipelineStep, error) {
	type resolvedStep struct {
		spec        StepSpec
		queue       string
		hash        string
		providerRef string
	}
	resolved := make([]resolvedStep, len(spec.Steps))
	for i, s := range spec.Steps {
		h, ok := e.Registry.Lookup(s.Kind)
		if !ok {
			return nil, fmt.Errorf("pipeline: no handler registered for step kind %q", s.Kind)
		}
		ref := StepRef{ID: s.ID, TenantID: tenantID, RunID: spec.ID, ScopeKind: s.ScopeKind, ScopeID: s.ScopeID, Kind: s.Kind}
		queue, err := h.Queue(ctx, ref)
		if err != nil {
			return nil, fmt.Errorf("pipeline: resolve queue for step %s: %w", s.ID, err)
		}
		hash, err := h.InputHash(ctx, ref)
		if err != nil {
			return nil, fmt.Errorf("pipeline: compute input hash for step %s: %w", s.ID, err)
		}
		var providerRef string
		if model, err := h.ModelRef(ctx, ref); err != nil {
			return nil, fmt.Errorf("pipeline: resolve model ref for step %s: %w", s.ID, err)
		} else if model != nil {
			providerRef = model.Backend + ":" + model.Model
		}
		resolved[i] = resolvedStep{spec: s, queue: queue, hash: hash, providerRef: providerRef}
	}

	params := make([]dbgen.InsertStepBatchParams, len(resolved))
	for i, r := range resolved {
		status := StatusPending
		if len(r.spec.DependsOn) == 0 {
			status = StatusQueued
		}
		params[i] = dbgen.InsertStepBatchParams{
			ID:            idconv.ToPg(r.spec.ID),
			TenantID:      idconv.ToPg(tenantID),
			RunID:         idconv.ToPg(spec.ID),
			ScopeKind:     r.spec.ScopeKind,
			ScopeID:       idconv.ToPg(r.spec.ScopeID),
			Kind:          r.spec.Kind,
			Queue:         r.queue,
			ProviderRef:   r.providerRef,
			Priority:      int16(r.spec.Priority),
			Status:        status,
			RemainingDeps: int32(len(r.spec.DependsOn)),
			InputHash:     r.hash,
		}
	}

	steps := make([]dbgen.PipelineStep, 0, len(params))
	var firstErr error
	if len(params) > 0 {
		qtx.InsertStepBatch(ctx, params).QueryRow(func(_ int, step dbgen.PipelineStep, err error) {
			if err != nil {
				if firstErr == nil {
					firstErr = err
				}
				return
			}
			steps = append(steps, step)
		})
		if firstErr != nil {
			return nil, fmt.Errorf("pipeline: insert steps: %w", firstErr)
		}
	}

	var depParams []dbgen.InsertStepDepBatchParams
	for _, r := range resolved {
		for _, dep := range r.spec.DependsOn {
			depParams = append(depParams, dbgen.InsertStepDepBatchParams{
				TenantID:        idconv.ToPg(tenantID),
				StepID:          idconv.ToPg(r.spec.ID),
				DependsOnStepID: idconv.ToPg(dep),
			})
		}
	}
	if len(depParams) > 0 {
		var depErr error
		qtx.InsertStepDepBatch(ctx, depParams).Exec(func(_ int, err error) {
			if err != nil && depErr == nil {
				depErr = err
			}
		})
		if depErr != nil {
			return nil, fmt.Errorf("pipeline: insert step deps: %w", depErr)
		}
	}

	return steps, nil
}

// enqueueReadySteps groups every "queued" step by (queue, kind), chunks
// each group to BatchChunkTarget using e.Estimator, and inserts one River
// job per chunk inside tx.
func (e *Engine) enqueueReadySteps(ctx context.Context, tx pgx.Tx, steps []dbgen.PipelineStep) error {
	type groupKey struct{ queue, kind string }
	groups := make(map[groupKey][]dbgen.PipelineStep)
	for _, s := range steps {
		if s.Status != StatusQueued {
			continue
		}
		key := groupKey{queue: s.Queue, kind: s.Kind}
		groups[key] = append(groups[key], s)
	}

	// Deterministic order keeps tests (and logs) reproducible.
	keys := make([]groupKey, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].queue != keys[j].queue {
			return keys[i].queue < keys[j].queue
		}
		return keys[i].kind < keys[j].kind
	})

	for _, key := range keys {
		group := groups[key]
		size := ChunkSize(e.Estimator(key.kind))
		metadata, err := json.Marshal(stepJobMetadata{Kind: key.kind})
		if err != nil {
			return err
		}
		for _, chunk := range ChunkIDs(stepIDs(group), size) {
			priority := minPriority(group, chunk)
			if _, err := e.River.InsertTx(ctx, tx, StepJobArgs{StepIDs: chunk}, &river.InsertOpts{
				Queue:       key.queue,
				Priority:    priority,
				MaxAttempts: MaxTransientAttempts,
				Metadata:    metadata,
				UniqueOpts: river.UniqueOpts{
					ByArgs:  true,
					ByQueue: true,
					ByState: readyUniqueStates,
				},
			}); err != nil {
				return err
			}
		}
	}
	return nil
}

func stepIDs(steps []dbgen.PipelineStep) []uuid.UUID {
	ids := make([]uuid.UUID, len(steps))
	for i, s := range steps {
		ids[i] = idconv.FromPg(s.ID)
	}
	return ids
}

func minPriority(steps []dbgen.PipelineStep, chunk []uuid.UUID) int {
	want := make(map[uuid.UUID]bool, len(chunk))
	for _, id := range chunk {
		want[id] = true
	}
	best := PriorityTrainBench
	for _, s := range steps {
		if !want[idconv.FromPg(s.ID)] {
			continue
		}
		if int(s.Priority) < best {
			best = int(s.Priority)
		}
	}
	return best
}
