#!/usr/bin/env bash
# One-time local dev bootstrap: generates every secret compose.yml needs
# (secrets/*.txt files plus the matching .env values) so a fresh
# `docker compose up --wait` needs no other manual step. Never run this
# against a real deployment; it generates and prints dev-only credentials.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

mkdir -p secrets

rand_b64_32() { head -c 32 /dev/urandom | base64 | tr -d '\n'; }
rand_alnum() { head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 40; }

# age-keygen only exists inside the backup image, not on the host, so an
# identity is generated by running that image once; deploy/backup/backup.sh
# derives the public recipient from this file itself (age-keygen -y), so
# nothing else needs to know the public key up front.
gen_age_identity() {
    if ! docker image inspect loomtale/backup:local >/dev/null 2>&1; then
        docker compose -f deploy/compose.yml build backup >/dev/null
    fi
    docker run --rm --entrypoint age-keygen loomtale/backup:local 2>/dev/null
}

write_secret_file() {
    file="secrets/$1"
    if [ -s "$file" ]; then
        echo "keeping existing $file"
        return
    fi
    printf '%s' "$2" > "$file"
    echo "wrote $file"
}

set_env_var() {
    key="$1"
    value="$2"
    if [ -f .env ] && grep -qE "^${key}=.+" .env; then
        echo "keeping existing .env value for $key"
        return
    fi
    if [ -f .env ] && grep -q "^${key}=" .env; then
        # Present but empty (e.g. copied from .env.example): fill it in
        # place instead of appending a duplicate key.
        awk -v k="$key" -v v="$value" -F= 'BEGIN{OFS="="} $1==k{$0=k"="v} {print}' .env > .env.tmp && mv .env.tmp .env
    else
        printf '%s=%s\n' "$key" "$value" >> .env
    fi
    echo "wrote .env: $key"
}

[ -f .env ] || cp .env.example .env

OWNER_PASSWORD="$(rand_alnum)"
APP_PASSWORD="$(rand_alnum)"
MINIO_ROOT_USER="loomtale-root"
MINIO_ROOT_PASSWORD="$(rand_alnum)"
MINIO_APP_ACCESS_KEY="loomtale-app"
MINIO_APP_SECRET_KEY="$(rand_alnum)"
MASTER_KEY="$(rand_b64_32)"

write_secret_file postgres_owner_password.txt "$OWNER_PASSWORD"
write_secret_file postgres_app_password.txt "$APP_PASSWORD"
write_secret_file minio_root_user.txt "$MINIO_ROOT_USER"
write_secret_file minio_root_password.txt "$MINIO_ROOT_PASSWORD"
write_secret_file master_key.txt "$MASTER_KEY"
if [ ! -s secrets/backup_encryption_key.txt ]; then
    write_secret_file backup_encryption_key.txt "$(gen_age_identity)"
else
    echo "keeping existing secrets/backup_encryption_key.txt"
fi
write_secret_file backup_target_credentials.txt "BACKUP_TARGET_ACCESS_KEY_ID=\nBACKUP_TARGET_SECRET_ACCESS_KEY=\n"

set_env_var POSTGRES_OWNER_PASSWORD "$(cat secrets/postgres_owner_password.txt)"
set_env_var POSTGRES_APP_PASSWORD "$(cat secrets/postgres_app_password.txt)"
set_env_var MINIO_APP_ACCESS_KEY "$MINIO_APP_ACCESS_KEY"
set_env_var MINIO_APP_SECRET_KEY "$MINIO_APP_SECRET_KEY"

echo "dev secrets ready: run 'make up' next."
