#!/usr/bin/env bash
# One-time local dev bootstrap: generates every secret compose.yml needs
# (secrets/*.txt files plus the matching .env values) so a fresh
# `docker compose up --wait` needs no other manual step. Never run this
# against a real deployment; it generates and prints dev-only credentials.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

mkdir -p secrets
umask 077

rand_b64_32() { head -c 32 /dev/urandom | base64 | tr -d '\n'; }
rand_alnum() { head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 40; }

# age-keygen only exists inside the backup image, not on the host, so an
# identity is generated by running that image once. Only the derived
# public recipient is ever wired into compose (BACKUP_ENCRYPTION_RECIPIENT
# in .env); the identity file below is written to secrets/ purely for the
# operator to copy somewhere safe (a password manager, offline storage)
# for the restore drill — no container ever mounts it.
#
# compose resolves every service's ${VAR:?...} interpolation while
# parsing the YAML, for `build backup` exactly as for `up`, even though a
# plain image build touches none of those values — and at this point in
# the script several of them (this very identity's own recipient,
# BACKUP_TARGET) cannot exist yet. Shell-environment overrides take
# precedence over --env-file, so dummy values here satisfy the
# interpolation for this one bootstrap build without touching .env.
gen_age_identity() {
    if ! docker image inspect loomtale/backup:local >/dev/null 2>&1; then
        POSTGRES_OWNER_PASSWORD=x POSTGRES_APP_PASSWORD=x POSTGRES_BACKUP_PASSWORD=x \
            MINIO_APP_ACCESS_KEY=x MINIO_APP_SECRET_KEY=x \
            MINIO_BACKUP_ACCESS_KEY=x MINIO_BACKUP_SECRET_KEY=x \
            BACKUP_TARGET=x BACKUP_TARGET_BUCKET=x BACKUP_ENCRYPTION_RECIPIENT=x \
            docker compose -f deploy/compose.yml build backup >/dev/null
    fi
    docker run --rm --entrypoint age-keygen loomtale/backup:local 2>/dev/null
}

age_recipient_from_identity() {
    docker run --rm -i --entrypoint age-keygen loomtale/backup:local -y < "$1" 2>/dev/null
}

write_secret_file() {
    file="secrets/$1"
    if [ -s "$file" ]; then
        echo "keeping existing $file"
        return
    fi
    printf '%s' "$2" > "$file"
    echo "wrote $file"
}

set_env_var() {
    key="$1"
    value="$2"
    if [ -f .env ] && grep -qE "^${key}=.+" .env; then
        echo "keeping existing .env value for $key"
        return
    fi
    if [ -f .env ] && grep -q "^${key}=" .env; then
        # Present but empty (e.g. copied from .env.example): fill it in
        # place instead of appending a duplicate key.
        awk -v k="$key" -v v="$value" -F= 'BEGIN{OFS="="} $1==k{$0=k"="v} {print}' .env > .env.tmp && mv .env.tmp .env
    else
        printf '%s=%s\n' "$key" "$value" >> .env
    fi
    echo "wrote .env: $key"
}

[ -f .env ] || cp .env.example .env

SUPERUSER_PASSWORD="$(rand_alnum)"
OWNER_PASSWORD="$(rand_alnum)"
APP_PASSWORD="$(rand_alnum)"
BACKUP_PASSWORD="$(rand_alnum)"
MINIO_ROOT_USER="loomtale-root"
MINIO_ROOT_PASSWORD="$(rand_alnum)"
MINIO_APP_ACCESS_KEY="loomtale-app"
MINIO_APP_SECRET_KEY="$(rand_alnum)"
MINIO_BACKUP_ACCESS_KEY="loomtale-backup"
MINIO_BACKUP_SECRET_KEY="$(rand_alnum)"
MASTER_KEY="$(rand_b64_32)"

write_secret_file postgres_superuser_password.txt "$SUPERUSER_PASSWORD"
write_secret_file postgres_owner_password.txt "$OWNER_PASSWORD"
write_secret_file postgres_app_password.txt "$APP_PASSWORD"
write_secret_file postgres_backup_password.txt "$BACKUP_PASSWORD"
write_secret_file minio_root_user.txt "$MINIO_ROOT_USER"
write_secret_file minio_root_password.txt "$MINIO_ROOT_PASSWORD"
write_secret_file master_key.txt "$MASTER_KEY"
if [ ! -s secrets/backup_encryption_key.txt ]; then
    write_secret_file backup_encryption_key.txt "$(gen_age_identity)"
else
    echo "keeping existing secrets/backup_encryption_key.txt"
fi
write_secret_file backup_target_credentials.txt "BACKUP_TARGET_ACCESS_KEY_ID=
BACKUP_TARGET_SECRET_ACCESS_KEY=
"

set_env_var POSTGRES_OWNER_PASSWORD "$(cat secrets/postgres_owner_password.txt)"
set_env_var POSTGRES_APP_PASSWORD "$(cat secrets/postgres_app_password.txt)"
set_env_var POSTGRES_BACKUP_PASSWORD "$(cat secrets/postgres_backup_password.txt)"
set_env_var MINIO_APP_ACCESS_KEY "$MINIO_APP_ACCESS_KEY"
set_env_var MINIO_APP_SECRET_KEY "$MINIO_APP_SECRET_KEY"
set_env_var MINIO_BACKUP_ACCESS_KEY "$MINIO_BACKUP_ACCESS_KEY"
set_env_var MINIO_BACKUP_SECRET_KEY "$MINIO_BACKUP_SECRET_KEY"
set_env_var BACKUP_ENCRYPTION_RECIPIENT "$(age_recipient_from_identity secrets/backup_encryption_key.txt)"

echo "dev secrets ready: run 'make up' next."
echo "keep secrets/backup_encryption_key.txt somewhere safe OUTSIDE this repo/machine for the restore drill; it is not mounted into any container."
