# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from loomtale.worker.v1 import align_pb2 as loomtale_dot_worker_dot_v1_dot_align__pb2


class AlignStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Align = channel.unary_stream(
                '/loomtale.worker.v1.Align/Align',
                request_serializer=loomtale_dot_worker_dot_v1_dot_align__pb2.AlignRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_align__pb2.AlignEvent.FromString,
                _registered_method=True)


class AlignServicer:
    """Missing associated documentation comment in .proto file."""

    def Align(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlignServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Align': grpc.unary_stream_rpc_method_handler(
                    servicer.Align,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_align__pb2.AlignRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_align__pb2.AlignEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomtale.worker.v1.Align', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomtale.worker.v1.Align', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Align:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Align(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomtale.worker.v1.Align/Align',
            loomtale_dot_worker_dot_v1_dot_align__pb2.AlignRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_align__pb2.AlignEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
