# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/align.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/align.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloomtale/worker/v1/align.proto\x12\x12loomtale.worker.v1\"\x85\x02\n\x0c\x41lignRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\"\n\raudio_get_url\x18\x02 \x01(\tR\x0b\x61udioGetUrl\x12\x12\n\x04text\x18\x03 \x01(\tR\x04text\x12$\n\x0eoutput_put_url\x18\x04 \x01(\tR\x0coutputPutUrl\x12\x44\n\x06params\x18\x05 \x03(\x0b\x32,.loomtale.worker.v1.AlignRequest.ParamsEntryR\x06params\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"6\n\rAlignProgress\x12\x10\n\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n\x05\x65ta_s\x18\x02 \x01(\x05R\x04\x65taS\"\xd9\x01\n\x0b\x41lignResult\x12\x1d\n\noutput_key\x18\x01 \x01(\tR\toutputKey\x12#\n\rsegment_count\x18\x02 \x01(\x05R\x0csegmentCount\x12I\n\x08metadata\x18\x03 \x03(\x0b\x32-.loomtale.worker.v1.AlignResult.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x91\x01\n\nAlignEvent\x12?\n\x08progress\x18\x01 \x01(\x0b\x32!.loomtale.worker.v1.AlignProgressH\x00R\x08progress\x12\x39\n\x06result\x18\x02 \x01(\x0b\x32\x1f.loomtale.worker.v1.AlignResultH\x00R\x06resultB\x07\n\x05\x65vent2T\n\x05\x41lign\x12K\n\x05\x41lign\x12 .loomtale.worker.v1.AlignRequest\x1a\x1e.loomtale.worker.v1.AlignEvent0\x01\x42<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.align_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_ALIGNREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_ALIGNREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_ALIGNRESULT_METADATAENTRY']._loaded_options = None
  _globals['_ALIGNRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ALIGNREQUEST']._serialized_start=55
  _globals['_ALIGNREQUEST']._serialized_end=316
  _globals['_ALIGNREQUEST_PARAMSENTRY']._serialized_start=259
  _globals['_ALIGNREQUEST_PARAMSENTRY']._serialized_end=316
  _globals['_ALIGNPROGRESS']._serialized_start=318
  _globals['_ALIGNPROGRESS']._serialized_end=372
  _globals['_ALIGNRESULT']._serialized_start=375
  _globals['_ALIGNRESULT']._serialized_end=592
  _globals['_ALIGNRESULT_METADATAENTRY']._serialized_start=533
  _globals['_ALIGNRESULT_METADATAENTRY']._serialized_end=592
  _globals['_ALIGNEVENT']._serialized_start=595
  _globals['_ALIGNEVENT']._serialized_end=740
  _globals['_ALIGN']._serialized_start=742
  _globals['_ALIGN']._serialized_end=826
# @@protoc_insertion_point(module_scope)
