# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/health.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1floomtale/worker/v1/health.proto\x12\x12loomtale.worker.v1\".\n\x12HealthCheckRequest\x12\x18\n\x07service\x18\x01 \x01(\tR\x07service\"\xa7\x01\n\x13HealthCheckResponse\x12\x46\n\x06status\x18\x01 \x01(\x0e\x32..loomtale.worker.v1.HealthCheckResponse.StatusR\x06status\"H\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SERVING\x10\x01\x12\x16\n\x12STATUS_NOT_SERVING\x10\x02\x32h\n\x0cWorkerHealth\x12X\n\x05\x43heck\x12&.loomtale.worker.v1.HealthCheckRequest\x1a\'.loomtale.worker.v1.HealthCheckResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=55
  _globals['_HEALTHCHECKREQUEST']._serialized_end=101
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=104
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=271
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=199
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=271
  _globals['_WORKERHEALTH']._serialized_start=273
  _globals['_WORKERHEALTH']._serialized_end=377
# @@protoc_insertion_point(module_scope)
