# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/train.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/train.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eloomtale/worker/v1/train.proto\x12\x12loomtale.worker.v1\"\x94\x02\n\x0cTrainRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\x1d\n\nbase_model\x18\x02 \x01(\tR\tbaseModel\x12&\n\x0f\x64\x61taset_get_url\x18\x03 \x01(\tR\rdatasetGetUrl\x12$\n\x0eoutput_put_url\x18\x04 \x01(\tR\x0coutputPutUrl\x12\x44\n\x06params\x18\x05 \x03(\x0b\x32,.loomtale.worker.v1.TrainRequest.ParamsEntryR\x06params\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"k\n\rTrainProgress\x12\x10\n\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n\x05\x65ta_s\x18\x02 \x01(\x05R\x04\x65taS\x12\x12\n\x04step\x18\x03 \x01(\x05R\x04step\x12\x1f\n\x0btotal_steps\x18\x04 \x01(\x05R\ntotalSteps\"\x1e\n\x08TrainLog\x12\x12\n\x04line\x18\x01 \x01(\tR\x04line\"\xb4\x01\n\x0bTrainResult\x12\x1d\n\noutput_key\x18\x01 \x01(\tR\toutputKey\x12I\n\x08metadata\x18\x02 \x03(\x0b\x32-.loomtale.worker.v1.TrainResult.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xc3\x01\n\nTrainEvent\x12?\n\x08progress\x18\x01 \x01(\x0b\x32!.loomtale.worker.v1.TrainProgressH\x00R\x08progress\x12\x30\n\x03log\x18\x02 \x01(\x0b\x32\x1c.loomtale.worker.v1.TrainLogH\x00R\x03log\x12\x39\n\x06result\x18\x03 \x01(\x0b\x32\x1f.loomtale.worker.v1.TrainResultH\x00R\x06resultB\x07\n\x05\x65vent2T\n\x05Train\x12K\n\x05Train\x12 .loomtale.worker.v1.TrainRequest\x1a\x1e.loomtale.worker.v1.TrainEvent0\x01\x42<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.train_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_TRAINREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINRESULT_METADATAENTRY']._loaded_options = None
  _globals['_TRAINRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=55
  _globals['_TRAINREQUEST']._serialized_end=331
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_start=274
  _globals['_TRAINREQUEST_PARAMSENTRY']._serialized_end=331
  _globals['_TRAINPROGRESS']._serialized_start=333
  _globals['_TRAINPROGRESS']._serialized_end=440
  _globals['_TRAINLOG']._serialized_start=442
  _globals['_TRAINLOG']._serialized_end=472
  _globals['_TRAINRESULT']._serialized_start=475
  _globals['_TRAINRESULT']._serialized_end=655
  _globals['_TRAINRESULT_METADATAENTRY']._serialized_start=596
  _globals['_TRAINRESULT_METADATAENTRY']._serialized_end=655
  _globals['_TRAINEVENT']._serialized_start=658
  _globals['_TRAINEVENT']._serialized_end=853
  _globals['_TRAIN']._serialized_start=855
  _globals['_TRAIN']._serialized_end=939
# @@protoc_insertion_point(module_scope)
