# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from loomtale.worker.v1 import train_pb2 as loomtale_dot_worker_dot_v1_dot_train__pb2


class TrainStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_stream(
                '/loomtale.worker.v1.Train/Train',
                request_serializer=loomtale_dot_worker_dot_v1_dot_train__pb2.TrainRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_train__pb2.TrainEvent.FromString,
                _registered_method=True)


class TrainServicer:
    """Missing associated documentation comment in .proto file."""

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_stream_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_train__pb2.TrainRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_train__pb2.TrainEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomtale.worker.v1.Train', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomtale.worker.v1.Train', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Train:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loomtale.worker.v1.Train/Train',
            loomtale_dot_worker_dot_v1_dot_train__pb2.TrainRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_train__pb2.TrainEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
