# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/tts.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cloomtale/worker/v1/tts.proto\x12\x12loomtale.worker.v1\"\x81\x02\n\x11SynthesizeRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\x14\n\x05voice\x18\x02 \x01(\tR\x05voice\x12\x12\n\x04text\x18\x03 \x01(\tR\x04text\x12$\n\x0eoutput_put_url\x18\x04 \x01(\tR\x0coutputPutUrl\x12I\n\x06params\x18\x05 \x03(\x0b\x32\x31.loomtale.worker.v1.SynthesizeRequest.ParamsEntryR\x06params\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\";\n\x12SynthesizeProgress\x12\x10\n\x03pct\x18\x01 \x01(\x05R\x03pct\x12\x13\n\x05\x65ta_s\x18\x02 \x01(\x05R\x04\x65taS\"\xdd\x01\n\x10SynthesizeResult\x12\x1d\n\noutput_key\x18\x01 \x01(\tR\toutputKey\x12\x1d\n\nduration_s\x18\x02 \x01(\x01R\tdurationS\x12N\n\x08metadata\x18\x03 \x03(\x0b\x32\x32.loomtale.worker.v1.SynthesizeResult.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xa0\x01\n\x0fSynthesizeEvent\x12\x44\n\x08progress\x18\x01 \x01(\x0b\x32&.loomtale.worker.v1.SynthesizeProgressH\x00R\x08progress\x12>\n\x06result\x18\x02 \x01(\x0b\x32$.loomtale.worker.v1.SynthesizeResultH\x00R\x06resultB\x07\n\x05\x65vent2a\n\x03TTS\x12Z\n\nSynthesize\x12%.loomtale.worker.v1.SynthesizeRequest\x1a#.loomtale.worker.v1.SynthesizeEvent0\x01\x42<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_SYNTHESIZEREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_SYNTHESIZEREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SYNTHESIZERESULT_METADATAENTRY']._loaded_options = None
  _globals['_SYNTHESIZERESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SYNTHESIZEREQUEST']._serialized_start=53
  _globals['_SYNTHESIZEREQUEST']._serialized_end=310
  _globals['_SYNTHESIZEREQUEST_PARAMSENTRY']._serialized_start=253
  _globals['_SYNTHESIZEREQUEST_PARAMSENTRY']._serialized_end=310
  _globals['_SYNTHESIZEPROGRESS']._serialized_start=312
  _globals['_SYNTHESIZEPROGRESS']._serialized_end=371
  _globals['_SYNTHESIZERESULT']._serialized_start=374
  _globals['_SYNTHESIZERESULT']._serialized_end=595
  _globals['_SYNTHESIZERESULT_METADATAENTRY']._serialized_start=536
  _globals['_SYNTHESIZERESULT_METADATAENTRY']._serialized_end=595
  _globals['_SYNTHESIZEEVENT']._serialized_start=598
  _globals['_SYNTHESIZEEVENT']._serialized_end=758
  _globals['_TTS']._serialized_start=760
  _globals['_TTS']._serialized_end=857
# @@protoc_insertion_point(module_scope)
