# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from loomtale.worker.v1 import vision_pb2 as loomtale_dot_worker_dot_v1_dot_vision__pb2


class VisionStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Score = channel.unary_unary(
                '/loomtale.worker.v1.Vision/Score',
                request_serializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.Depth = channel.unary_unary(
                '/loomtale.worker.v1.Vision/Depth',
                request_serializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthResponse.FromString,
                _registered_method=True)


class VisionServicer:
    """Missing associated documentation comment in .proto file."""

    def Score(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Depth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Score': grpc.unary_unary_rpc_method_handler(
                    servicer.Score,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreResponse.SerializeToString,
            ),
            'Depth': grpc.unary_unary_rpc_method_handler(
                    servicer.Depth,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomtale.worker.v1.Vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomtale.worker.v1.Vision', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vision:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Score(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Vision/Score',
            loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_vision__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Depth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Vision/Depth',
            loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_vision__pb2.DepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
