# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/vision.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1floomtale/worker/v1/vision.proto\x12\x12loomtale.worker.v1\"\xcb\x01\n\x0cScoreRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\"\n\rimage_get_url\x18\x02 \x01(\tR\x0bimageGetUrl\x12\x44\n\x06params\x18\x03 \x03(\x0b\x32,.loomtale.worker.v1.ScoreRequest.ParamsEntryR\x06params\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xaf\x01\n\rScoreResponse\x12\x14\n\x05score\x18\x01 \x01(\x01R\x05score\x12K\n\x08metadata\x18\x02 \x03(\x0b\x32/.loomtale.worker.v1.ScoreResponse.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xf1\x01\n\x0c\x44\x65pthRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\"\n\rimage_get_url\x18\x02 \x01(\tR\x0bimageGetUrl\x12$\n\x0eoutput_put_url\x18\x03 \x01(\tR\x0coutputPutUrl\x12\x44\n\x06params\x18\x04 \x03(\x0b\x32,.loomtale.worker.v1.DepthRequest.ParamsEntryR\x06params\x1a\x39\n\x0bParamsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\".\n\rDepthResponse\x12\x1d\n\noutput_key\x18\x01 \x01(\tR\toutputKey2\xa4\x01\n\x06Vision\x12L\n\x05Score\x12 .loomtale.worker.v1.ScoreRequest\x1a!.loomtale.worker.v1.ScoreResponse\x12L\n\x05\x44\x65pth\x12 .loomtale.worker.v1.DepthRequest\x1a!.loomtale.worker.v1.DepthResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_SCOREREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_SCOREREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SCORERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_SCORERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DEPTHREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_DEPTHREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_SCOREREQUEST']._serialized_start=56
  _globals['_SCOREREQUEST']._serialized_end=259
  _globals['_SCOREREQUEST_PARAMSENTRY']._serialized_start=202
  _globals['_SCOREREQUEST_PARAMSENTRY']._serialized_end=259
  _globals['_SCORERESPONSE']._serialized_start=262
  _globals['_SCORERESPONSE']._serialized_end=437
  _globals['_SCORERESPONSE_METADATAENTRY']._serialized_start=378
  _globals['_SCORERESPONSE_METADATAENTRY']._serialized_end=437
  _globals['_DEPTHREQUEST']._serialized_start=440
  _globals['_DEPTHREQUEST']._serialized_end=681
  _globals['_DEPTHREQUEST_PARAMSENTRY']._serialized_start=202
  _globals['_DEPTHREQUEST_PARAMSENTRY']._serialized_end=259
  _globals['_DEPTHRESPONSE']._serialized_start=683
  _globals['_DEPTHRESPONSE']._serialized_end=729
  _globals['_VISION']._serialized_start=732
  _globals['_VISION']._serialized_end=896
# @@protoc_insertion_point(module_scope)
