# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loomtale/worker/v1/worker.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'loomtale/worker/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1floomtale/worker/v1/worker.proto\x12\x12loomtale.worker.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x02ok\x18\x01 \x01(\x08R\x02ok\"\x14\n\x12ListEnginesRequest\"\xa6\x01\n\nEngineInfo\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n\x07license\x18\x03 \x01(\tR\x07license\x12\x1c\n\tinstalled\x18\x04 \x01(\x08R\tinstalled\x12\x16\n\x06loaded\x18\x05 \x01(\x08R\x06loaded\x12 \n\x0cvram_held_mb\x18\x06 \x01(\x03R\nvramHeldMb\"O\n\x13ListEnginesResponse\x12\x38\n\x07\x65ngines\x18\x01 \x03(\x0b\x32\x1e.loomtale.worker.v1.EngineInfoR\x07\x65ngines\"@\n\x10LoadModelRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\x12\x14\n\x05model\x18\x02 \x01(\tR\x05model\"M\n\x11LoadModelResponse\x12\x16\n\x06loaded\x18\x01 \x01(\x08R\x06loaded\x12 \n\x0cvram_held_mb\x18\x02 \x01(\x03R\nvramHeldMb\",\n\x12UnloadModelRequest\x12\x16\n\x06\x65ngine\x18\x01 \x01(\tR\x06\x65ngine\"1\n\x13UnloadModelResponse\x12\x1a\n\x08unloaded\x18\x01 \x01(\x08R\x08unloaded\"\x12\n\x10GpuStatusRequest\"\x91\x01\n\x11GpuStatusResponse\x12\x1f\n\x0bgpu_present\x18\x01 \x01(\x08R\ngpuPresent\x12\x19\n\x08total_mb\x18\x02 \x01(\x03R\x07totalMb\x12\x17\n\x07\x66ree_mb\x18\x03 \x01(\x03R\x06\x66reeMb\x12\'\n\x0fresident_engine\x18\x04 \x01(\tR\x0eresidentEngine2\xcd\x03\n\x06Worker\x12O\n\x06Health\x12!.loomtale.worker.v1.HealthRequest\x1a\".loomtale.worker.v1.HealthResponse\x12^\n\x0bListEngines\x12&.loomtale.worker.v1.ListEnginesRequest\x1a\'.loomtale.worker.v1.ListEnginesResponse\x12X\n\tLoadModel\x12$.loomtale.worker.v1.LoadModelRequest\x1a%.loomtale.worker.v1.LoadModelResponse\x12^\n\x0bUnloadModel\x12&.loomtale.worker.v1.UnloadModelRequest\x1a\'.loomtale.worker.v1.UnloadModelResponse\x12X\n\tGpuStatus\x12$.loomtale.worker.v1.GpuStatusRequest\x1a%.loomtale.worker.v1.GpuStatusResponseB<Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loomtale.worker.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:loomtale/api/internal/workerpb/loomtale/worker/v1;workerv1'
  _globals['_HEALTHREQUEST']._serialized_start=55
  _globals['_HEALTHREQUEST']._serialized_end=70
  _globals['_HEALTHRESPONSE']._serialized_start=72
  _globals['_HEALTHRESPONSE']._serialized_end=104
  _globals['_LISTENGINESREQUEST']._serialized_start=106
  _globals['_LISTENGINESREQUEST']._serialized_end=126
  _globals['_ENGINEINFO']._serialized_start=129
  _globals['_ENGINEINFO']._serialized_end=295
  _globals['_LISTENGINESRESPONSE']._serialized_start=297
  _globals['_LISTENGINESRESPONSE']._serialized_end=376
  _globals['_LOADMODELREQUEST']._serialized_start=378
  _globals['_LOADMODELREQUEST']._serialized_end=442
  _globals['_LOADMODELRESPONSE']._serialized_start=444
  _globals['_LOADMODELRESPONSE']._serialized_end=521
  _globals['_UNLOADMODELREQUEST']._serialized_start=523
  _globals['_UNLOADMODELREQUEST']._serialized_end=567
  _globals['_UNLOADMODELRESPONSE']._serialized_start=569
  _globals['_UNLOADMODELRESPONSE']._serialized_end=618
  _globals['_GPUSTATUSREQUEST']._serialized_start=620
  _globals['_GPUSTATUSREQUEST']._serialized_end=638
  _globals['_GPUSTATUSRESPONSE']._serialized_start=641
  _globals['_GPUSTATUSRESPONSE']._serialized_end=786
  _globals['_WORKER']._serialized_start=789
  _globals['_WORKER']._serialized_end=1250
# @@protoc_insertion_point(module_scope)
