# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from loomtale.worker.v1 import worker_pb2 as loomtale_dot_worker_dot_v1_dot_worker__pb2


class WorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/loomtale.worker.v1.Worker/Health',
                request_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListEngines = channel.unary_unary(
                '/loomtale.worker.v1.Worker/ListEngines',
                request_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/loomtale.worker.v1.Worker/LoadModel',
                request_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/loomtale.worker.v1.Worker/UnloadModel',
                request_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.GpuStatus = channel.unary_unary(
                '/loomtale.worker.v1.Worker/GpuStatus',
                request_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusRequest.SerializeToString,
                response_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusResponse.FromString,
                _registered_method=True)


class WorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Health reports process liveness (distinct from WorkerHealth.Check,
        which phase 1 already wired for the buf round-trip check).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEngines(self, request, context):
        """ListEngines reports every engine this worker process knows about,
        whether or not its weights are present on disk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """LoadModel makes an engine resident. Returns FAILED_PRECONDITION
        engine_not_installed if the engine's weights are not on disk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """UnloadModel releases whatever engine is currently resident, if any.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GpuStatus(self, request, context):
        """GpuStatus reports live VRAM and the resident engine, used by the Go
        residency manager's app-side proof step.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.SerializeToString,
            ),
            'ListEngines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEngines,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelResponse.SerializeToString,
            ),
            'GpuStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GpuStatus,
                    request_deserializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusRequest.FromString,
                    response_serializer=loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loomtale.worker.v1.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loomtale.worker.v1.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Worker/Health',
            loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEngines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Worker/ListEngines',
            loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_worker__pb2.ListEnginesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Worker/LoadModel',
            loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_worker__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Worker/UnloadModel',
            loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_worker__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GpuStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loomtale.worker.v1.Worker/GpuStatus',
            loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusRequest.SerializeToString,
            loomtale_dot_worker_dot_v1_dot_worker__pb2.GpuStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
