/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsLlmRouteImport } from './routes/_app/settings/llm'
import { Route as AppSettingsModelsRouteImport } from './routes/_app/settings/models'
import { Route as AppSettingsStylesRouteImport } from './routes/_app/settings/styles'
import { Route as AppSettingsVoicesRouteImport } from './routes/_app/settings/voices'
import { Route as AppProjectsSeriesIdIndexRouteImport } from './routes/_app/projects/$seriesId/index'
import { Route as AppProjectsSeriesIdBibleRouteImport } from './routes/_app/projects/$seriesId/bible'
import { Route as AppProjectsSeriesIdCharactersIndexRouteImport } from './routes/_app/projects/$seriesId/characters/index'
import { Route as AppProjectsSeriesIdEpisodesEpisodeIdRouteImport } from './routes/_app/projects/$seriesId/episodes/$episodeId'
import { Route as AppProjectsSeriesIdRenderEpisodeIdRouteImport } from './routes/_app/projects/$seriesId/render/$episodeId'
import { Route as AppProjectsSeriesIdStoryboardEpisodeIdRouteImport } from './routes/_app/projects/$seriesId/storyboard/$episodeId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLlmRoute = AppSettingsLlmRouteImport.update({
  id: '/settings/llm',
  path: '/settings/llm',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsModelsRoute = AppSettingsModelsRouteImport.update({
  id: '/settings/models',
  path: '/settings/models',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsStylesRoute = AppSettingsStylesRouteImport.update({
  id: '/settings/styles',
  path: '/settings/styles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsVoicesRoute = AppSettingsVoicesRouteImport.update({
  id: '/settings/voices',
  path: '/settings/voices',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSeriesIdIndexRoute =
  AppProjectsSeriesIdIndexRouteImport.update({
    id: '/projects/$seriesId/',
    path: '/projects/$seriesId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdBibleRoute =
  AppProjectsSeriesIdBibleRouteImport.update({
    id: '/projects/$seriesId/bible',
    path: '/projects/$seriesId/bible',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdCharactersIndexRoute =
  AppProjectsSeriesIdCharactersIndexRouteImport.update({
    id: '/projects/$seriesId/characters/',
    path: '/projects/$seriesId/characters/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdEpisodesEpisodeIdRoute =
  AppProjectsSeriesIdEpisodesEpisodeIdRouteImport.update({
    id: '/projects/$seriesId/episodes/$episodeId',
    path: '/projects/$seriesId/episodes/$episodeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdRenderEpisodeIdRoute =
  AppProjectsSeriesIdRenderEpisodeIdRouteImport.update({
    id: '/projects/$seriesId/render/$episodeId',
    path: '/projects/$seriesId/render/$episodeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdStoryboardEpisodeIdRoute =
  AppProjectsSeriesIdStoryboardEpisodeIdRouteImport.update({
    id: '/projects/$seriesId/storyboard/$episodeId',
    path: '/projects/$seriesId/storyboard/$episodeId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/library': typeof AppLibraryRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/llm': typeof AppSettingsLlmRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/styles': typeof AppSettingsStylesRoute
  '/settings/voices': typeof AppSettingsVoicesRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/projects/$seriesId/': typeof AppProjectsSeriesIdIndexRoute
  '/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
  '/projects/$seriesId/render/$episodeId': typeof AppProjectsSeriesIdRenderEpisodeIdRoute
  '/projects/$seriesId/storyboard/$episodeId': typeof AppProjectsSeriesIdStoryboardEpisodeIdRoute
  '/projects/$seriesId/characters/': typeof AppProjectsSeriesIdCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/library': typeof AppLibraryRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/llm': typeof AppSettingsLlmRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/styles': typeof AppSettingsStylesRoute
  '/settings/voices': typeof AppSettingsVoicesRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/projects/$seriesId': typeof AppProjectsSeriesIdIndexRoute
  '/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
  '/projects/$seriesId/render/$episodeId': typeof AppProjectsSeriesIdRenderEpisodeIdRoute
  '/projects/$seriesId/storyboard/$episodeId': typeof AppProjectsSeriesIdStoryboardEpisodeIdRoute
  '/projects/$seriesId/characters': typeof AppProjectsSeriesIdCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/import': typeof AppImportRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/llm': typeof AppSettingsLlmRoute
  '/_app/settings/models': typeof AppSettingsModelsRoute
  '/_app/settings/styles': typeof AppSettingsStylesRoute
  '/_app/settings/voices': typeof AppSettingsVoicesRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/_app/projects/$seriesId/': typeof AppProjectsSeriesIdIndexRoute
  '/_app/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
  '/_app/projects/$seriesId/render/$episodeId': typeof AppProjectsSeriesIdRenderEpisodeIdRoute
  '/_app/projects/$seriesId/storyboard/$episodeId': typeof AppProjectsSeriesIdStoryboardEpisodeIdRoute
  '/_app/projects/$seriesId/characters/': typeof AppProjectsSeriesIdCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/import'
    | '/jobs'
    | '/library'
    | '/settings/account'
    | '/settings/llm'
    | '/settings/models'
    | '/settings/styles'
    | '/settings/voices'
    | '/projects/'
    | '/projects/$seriesId/bible'
    | '/projects/$seriesId/'
    | '/projects/$seriesId/episodes/$episodeId'
    | '/projects/$seriesId/render/$episodeId'
    | '/projects/$seriesId/storyboard/$episodeId'
    | '/projects/$seriesId/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/jobs'
    | '/library'
    | '/'
    | '/settings/account'
    | '/settings/llm'
    | '/settings/models'
    | '/settings/styles'
    | '/settings/voices'
    | '/projects'
    | '/projects/$seriesId/bible'
    | '/projects/$seriesId'
    | '/projects/$seriesId/episodes/$episodeId'
    | '/projects/$seriesId/render/$episodeId'
    | '/projects/$seriesId/storyboard/$episodeId'
    | '/projects/$seriesId/characters'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/import'
    | '/_app/jobs'
    | '/_app/library'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/llm'
    | '/_app/settings/models'
    | '/_app/settings/styles'
    | '/_app/settings/voices'
    | '/_app/projects/'
    | '/_app/projects/$seriesId/bible'
    | '/_app/projects/$seriesId/'
    | '/_app/projects/$seriesId/episodes/$episodeId'
    | '/_app/projects/$seriesId/render/$episodeId'
    | '/_app/projects/$seriesId/storyboard/$episodeId'
    | '/_app/projects/$seriesId/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/llm': {
      id: '/_app/settings/llm'
      path: '/settings/llm'
      fullPath: '/settings/llm'
      preLoaderRoute: typeof AppSettingsLlmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/models': {
      id: '/_app/settings/models'
      path: '/settings/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof AppSettingsModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/styles': {
      id: '/_app/settings/styles'
      path: '/settings/styles'
      fullPath: '/settings/styles'
      preLoaderRoute: typeof AppSettingsStylesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/voices': {
      id: '/_app/settings/voices'
      path: '/settings/voices'
      fullPath: '/settings/voices'
      preLoaderRoute: typeof AppSettingsVoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/': {
      id: '/_app/projects/$seriesId/'
      path: '/projects/$seriesId'
      fullPath: '/projects/$seriesId/'
      preLoaderRoute: typeof AppProjectsSeriesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/bible': {
      id: '/_app/projects/$seriesId/bible'
      path: '/projects/$seriesId/bible'
      fullPath: '/projects/$seriesId/bible'
      preLoaderRoute: typeof AppProjectsSeriesIdBibleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/characters/': {
      id: '/_app/projects/$seriesId/characters/'
      path: '/projects/$seriesId/characters'
      fullPath: '/projects/$seriesId/characters/'
      preLoaderRoute: typeof AppProjectsSeriesIdCharactersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/episodes/$episodeId': {
      id: '/_app/projects/$seriesId/episodes/$episodeId'
      path: '/projects/$seriesId/episodes/$episodeId'
      fullPath: '/projects/$seriesId/episodes/$episodeId'
      preLoaderRoute: typeof AppProjectsSeriesIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/render/$episodeId': {
      id: '/_app/projects/$seriesId/render/$episodeId'
      path: '/projects/$seriesId/render/$episodeId'
      fullPath: '/projects/$seriesId/render/$episodeId'
      preLoaderRoute: typeof AppProjectsSeriesIdRenderEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/storyboard/$episodeId': {
      id: '/_app/projects/$seriesId/storyboard/$episodeId'
      path: '/projects/$seriesId/storyboard/$episodeId'
      fullPath: '/projects/$seriesId/storyboard/$episodeId'
      preLoaderRoute: typeof AppProjectsSeriesIdStoryboardEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsLlmRoute: typeof AppSettingsLlmRoute
  AppSettingsModelsRoute: typeof AppSettingsModelsRoute
  AppSettingsStylesRoute: typeof AppSettingsStylesRoute
  AppSettingsVoicesRoute: typeof AppSettingsVoicesRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsSeriesIdBibleRoute: typeof AppProjectsSeriesIdBibleRoute
  AppProjectsSeriesIdIndexRoute: typeof AppProjectsSeriesIdIndexRoute
  AppProjectsSeriesIdEpisodesEpisodeIdRoute: typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
  AppProjectsSeriesIdRenderEpisodeIdRoute: typeof AppProjectsSeriesIdRenderEpisodeIdRoute
  AppProjectsSeriesIdStoryboardEpisodeIdRoute: typeof AppProjectsSeriesIdStoryboardEpisodeIdRoute
  AppProjectsSeriesIdCharactersIndexRoute: typeof AppProjectsSeriesIdCharactersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppJobsRoute: AppJobsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsLlmRoute: AppSettingsLlmRoute,
  AppSettingsModelsRoute: AppSettingsModelsRoute,
  AppSettingsStylesRoute: AppSettingsStylesRoute,
  AppSettingsVoicesRoute: AppSettingsVoicesRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsSeriesIdBibleRoute: AppProjectsSeriesIdBibleRoute,
  AppProjectsSeriesIdIndexRoute: AppProjectsSeriesIdIndexRoute,
  AppProjectsSeriesIdEpisodesEpisodeIdRoute:
    AppProjectsSeriesIdEpisodesEpisodeIdRoute,
  AppProjectsSeriesIdRenderEpisodeIdRoute:
    AppProjectsSeriesIdRenderEpisodeIdRoute,
  AppProjectsSeriesIdStoryboardEpisodeIdRoute:
    AppProjectsSeriesIdStoryboardEpisodeIdRoute,
  AppProjectsSeriesIdCharactersIndexRoute:
    AppProjectsSeriesIdCharactersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
