/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsLlmRouteImport } from './routes/_app/settings/llm'
import { Route as AppProjectsSeriesIdIndexRouteImport } from './routes/_app/projects/$seriesId/index'
import { Route as AppProjectsSeriesIdBibleRouteImport } from './routes/_app/projects/$seriesId/bible'
import { Route as AppProjectsSeriesIdEpisodesEpisodeIdRouteImport } from './routes/_app/projects/$seriesId/episodes/$episodeId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLlmRoute = AppSettingsLlmRouteImport.update({
  id: '/settings/llm',
  path: '/settings/llm',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSeriesIdIndexRoute =
  AppProjectsSeriesIdIndexRouteImport.update({
    id: '/projects/$seriesId/',
    path: '/projects/$seriesId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdBibleRoute =
  AppProjectsSeriesIdBibleRouteImport.update({
    id: '/projects/$seriesId/bible',
    path: '/projects/$seriesId/bible',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsSeriesIdEpisodesEpisodeIdRoute =
  AppProjectsSeriesIdEpisodesEpisodeIdRouteImport.update({
    id: '/projects/$seriesId/episodes/$episodeId',
    path: '/projects/$seriesId/episodes/$episodeId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/llm': typeof AppSettingsLlmRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/projects/$seriesId/': typeof AppProjectsSeriesIdIndexRoute
  '/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/jobs': typeof AppJobsRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/llm': typeof AppSettingsLlmRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/projects/$seriesId': typeof AppProjectsSeriesIdIndexRoute
  '/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/import': typeof AppImportRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/llm': typeof AppSettingsLlmRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$seriesId/bible': typeof AppProjectsSeriesIdBibleRoute
  '/_app/projects/$seriesId/': typeof AppProjectsSeriesIdIndexRoute
  '/_app/projects/$seriesId/episodes/$episodeId': typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/import'
    | '/jobs'
    | '/settings/account'
    | '/settings/llm'
    | '/projects/'
    | '/projects/$seriesId/bible'
    | '/projects/$seriesId/'
    | '/projects/$seriesId/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/jobs'
    | '/'
    | '/settings/account'
    | '/settings/llm'
    | '/projects'
    | '/projects/$seriesId/bible'
    | '/projects/$seriesId'
    | '/projects/$seriesId/episodes/$episodeId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/import'
    | '/_app/jobs'
    | '/_app/'
    | '/_app/settings/account'
    | '/_app/settings/llm'
    | '/_app/projects/'
    | '/_app/projects/$seriesId/bible'
    | '/_app/projects/$seriesId/'
    | '/_app/projects/$seriesId/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/llm': {
      id: '/_app/settings/llm'
      path: '/settings/llm'
      fullPath: '/settings/llm'
      preLoaderRoute: typeof AppSettingsLlmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/': {
      id: '/_app/projects/$seriesId/'
      path: '/projects/$seriesId'
      fullPath: '/projects/$seriesId/'
      preLoaderRoute: typeof AppProjectsSeriesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/bible': {
      id: '/_app/projects/$seriesId/bible'
      path: '/projects/$seriesId/bible'
      fullPath: '/projects/$seriesId/bible'
      preLoaderRoute: typeof AppProjectsSeriesIdBibleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$seriesId/episodes/$episodeId': {
      id: '/_app/projects/$seriesId/episodes/$episodeId'
      path: '/projects/$seriesId/episodes/$episodeId'
      fullPath: '/projects/$seriesId/episodes/$episodeId'
      preLoaderRoute: typeof AppProjectsSeriesIdEpisodesEpisodeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppJobsRoute: typeof AppJobsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsLlmRoute: typeof AppSettingsLlmRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsSeriesIdBibleRoute: typeof AppProjectsSeriesIdBibleRoute
  AppProjectsSeriesIdIndexRoute: typeof AppProjectsSeriesIdIndexRoute
  AppProjectsSeriesIdEpisodesEpisodeIdRoute: typeof AppProjectsSeriesIdEpisodesEpisodeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppJobsRoute: AppJobsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsLlmRoute: AppSettingsLlmRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsSeriesIdBibleRoute: AppProjectsSeriesIdBibleRoute,
  AppProjectsSeriesIdIndexRoute: AppProjectsSeriesIdIndexRoute,
  AppProjectsSeriesIdEpisodesEpisodeIdRoute:
    AppProjectsSeriesIdEpisodesEpisodeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
