-- +goose Up

-- A character of a series. Names are kept per language so the scene
-- split can map a name the LLM emits (in any of them) back to this row;
-- the LLM never sees or returns ids. `profile` is the text pinned into
-- every LLM request for the series while `pinned` is set.
CREATE TABLE characters (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    series_id uuid NOT NULL,
    name_orig text NOT NULL DEFAULT '',
    name_en text NOT NULL DEFAULT '',
    name_vi text NOT NULL DEFAULT '',
    role text NOT NULL DEFAULT '',
    appearance_prompt text NOT NULL DEFAULT '',
    negative_prompt text NOT NULL DEFAULT '',
    trigger_token text NOT NULL DEFAULT '',
    profile text NOT NULL DEFAULT '',
    pinned boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT characters_tenant_id_id_key UNIQUE (tenant_id, id),
    CONSTRAINT characters_tenant_series_fkey FOREIGN KEY (tenant_id, series_id)
        REFERENCES series (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT characters_has_a_name CHECK (name_orig <> '' OR name_en <> '' OR name_vi <> '')
);
CREATE INDEX characters_series_idx ON characters (tenant_id, series_id);

-- Reference images of a character (uploaded, or generated by the sheet
-- workflow), each with an angle label and an approval flag.
CREATE TABLE character_refs (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    character_id uuid NOT NULL,
    asset_id uuid NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    angle text NOT NULL DEFAULT '',
    approved boolean NOT NULL DEFAULT false,
    origin text NOT NULL DEFAULT 'upload' CHECK (origin IN ('upload', 'generated')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT character_refs_tenant_character_fkey FOREIGN KEY (tenant_id, character_id)
        REFERENCES characters (tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX character_refs_character_idx ON character_refs (tenant_id, character_id);

-- Trained LoRA versions. weights_file is the file name on the models
-- volume that a ComfyUI LoRA loader references once training finished.
CREATE TABLE character_loras (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    character_id uuid NOT NULL,
    version integer NOT NULL,
    dataset_asset_ids uuid[] NOT NULL DEFAULT '{}',
    trainer_params jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'training', 'ready', 'failed')),
    weights_asset_id uuid REFERENCES assets (id) ON DELETE SET NULL,
    weights_file text NOT NULL DEFAULT '',
    step_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT character_loras_tenant_character_fkey FOREIGN KEY (tenant_id, character_id)
        REFERENCES characters (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT character_loras_character_version_key UNIQUE (character_id, version)
);

-- One voice per character and narrated language.
CREATE TABLE character_voices (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    character_id uuid NOT NULL,
    lang text NOT NULL CHECK (lang IN ('en', 'vi')),
    engine text NOT NULL,
    voice_preset_id uuid,
    params jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- The latest "Preview line" synthesis with this voice.
    preview_asset_id uuid REFERENCES assets (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT character_voices_tenant_character_fkey FOREIGN KEY (tenant_id, character_id)
        REFERENCES characters (tenant_id, id) ON DELETE CASCADE,
    -- MATCH SIMPLE: skipped while voice_preset_id is null. Deleting a
    -- preset in use is refused rather than silently changing a voice.
    CONSTRAINT character_voices_tenant_preset_fkey FOREIGN KEY (tenant_id, voice_preset_id)
        REFERENCES voice_presets (tenant_id, id),
    CONSTRAINT character_voices_character_lang_key UNIQUE (character_id, lang)
);

-- The narrator's voice per series and language: the narrator is not a
-- character row, but its segments still need a voice.
CREATE TABLE narrator_voices (
    id uuid PRIMARY KEY,
    tenant_id uuid NOT NULL,
    series_id uuid NOT NULL,
    lang text NOT NULL CHECK (lang IN ('en', 'vi')),
    engine text NOT NULL,
    voice_preset_id uuid,
    params jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT narrator_voices_tenant_series_fkey FOREIGN KEY (tenant_id, series_id)
        REFERENCES series (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT narrator_voices_tenant_preset_fkey FOREIGN KEY (tenant_id, voice_preset_id)
        REFERENCES voice_presets (tenant_id, id),
    CONSTRAINT narrator_voices_series_lang_key UNIQUE (series_id, lang)
);

-- +goose Down
DROP TABLE narrator_voices;
DROP TABLE character_voices;
DROP TABLE character_loras;
DROP TABLE character_refs;
DROP TABLE characters;
